function ca_anchor_page(P, R, fname)
% CA_ANCHOR_PAGE  Review page for the tension anchors and the back plate: each check next to a
%   dimensioned diagram. Numbers from P and R only; figures reports/figures/ta_*.png from ca_draw.
fid = fopen(fname, 'w');
w = @(varargin) fprintf(fid, [varargin{1} '\n'], varargin{2:end});
Y = R.typ(1);  an = P.an;  bp = P.bp;  C = R.cone(1);  H = R.hk;  fc = P.fc;  sq = sqrt(fc);
kN = 1e-3;  Ab12 = pi*P.cb.db^2/4;  Fyb = P.st.Fy(bp.grade);
rr = R.rows;  row = @(s) rr(find(strncmp(rr(:,2), s, numel(s)), 1), :);
dc = @(s) subsref(row(s), substruct('{}', {4}))./subsref(row(s), substruct('{}', {5}));
w('<!doctype html><html><head><meta charset="utf-8"><title>Anchorage check</title>');
w(['<style>body{background:#fff;font-family:Helvetica,Arial,sans-serif;max-width:1250px;margin:24px auto;padding:0 16px;color:#111;line-height:1.45}' ...
   'h1{font-size:23px}h2{font-size:18px;margin-top:30px;border-bottom:1px solid #ccc}' ...
   '.row{display:grid;grid-template-columns:minmax(0,1.1fr) minmax(0,1fr);gap:18px;align-items:start;margin:12px 0}' ...
   '@media (max-width:900px){.row{grid-template-columns:1fr}}' ...
   '.row img{width:100%%;border:1px solid #ddd}.calc{font-size:14px}.calc ol{padding-left:20px;margin:0}.calc li{margin:5px 0}' ...
   '.ok{color:#1e6b32;font-weight:bold}.note{font-size:13px;color:#444}' ...
   '.tw{overflow-x:auto}table{border-collapse:collapse;font-size:13px;margin:10px 0}td,th{border:1px solid #ccc;padding:3px 6px;text-align:right}th:first-child,td:first-child{text-align:left}</style></head><body>']);
w('<h1>Anchorage check: 2 threaded rods %s %s, back plate PL %gx%gx%g %s, the beam bars and the joint</h1>', an.thr, an.grade, bp.t, bp.h, bp.w, P.st.name{bp.grade});
w('<p>2026-10-02, review page. Type E (edge) step by step; table for the four types at the end. ACI 318-19 chapter 17 (SI), concrete cracked, f''<sub>c</sub> = %.2f MPa. Every length used is drawn in the diagram next to it.</p>', fc);
w('<p><b>Model.</b> The anchors are deformed bars, but their bond is ignored: all of the pull goes to the back plate, which bears on the concrete behind the far column bars like the head of a headed anchor. The concrete in front of it is held by the top bars of the beam in line (anchor reinforcement, ACI 17.5.2.1), because the concrete alone cannot hold it (section 6).</p>');

% ---- 1. geometry and force
w('<h2>1. Where they are, and the force</h2><div class="row"><div><img src="figures/ta_geo.png" alt="plan"></div><div class="calc"><ol>');
w('<li>Two anchors at |v| = %g (s = %g), z = %+g, from %g mm outside the face to u = %.0f.</li>', an.vT, 2*an.vT, Y.zT, an.out, an.uT);
w('<li>Back plate bearing face at u = %g: %g mm behind the far ties (outer face at %g). The end of the bars is %.0f mm from the far face (covered by the slab later).</li>', bp.u, bp.u - (P.col.b - P.col.cover), P.col.b - P.col.cover, P.col.b - an.uT);
w('<li>Clear distances: %.0f to the front mid-face bar, %.0f from the nut corners to the far mid-face bar, %.0f to the rods of the steel column.</li>', an.vT - an.db/2 - P.col.db/2, an.vT - an.nut/sqrt(3) - P.col.db/2, P.rod.p - P.rod.db/2 - an.vT - an.db/2);
w('<li>Pull on the two anchors (end plate page, step 1): T = <b>%.1f kN</b>; per anchor T<sub>a</sub> = <b>%.1f kN</b>.</li>', Y.T*kN, Y.Ta*kN);
w('<li>Seismic (17.10.5): E<sub>v</sub> is %.0f%% of the pull (&gt; 20%%); option 17.10.5.3(d) amplifies only E<sub>h</sub>, which is zero here. With anchor reinforcement no further reduction applies (17.10.5.5).</li>', 100*R.kase(1).fE);
w('</ol></div></div>');

% ---- 2. the bar
phiNsa = 0.75*an.Ase*an.futa;  phiVsa = 0.80*0.65*0.6*an.Ase*an.futa;
Vt = hypot(Y.Vu/4, Y.Hc/2);  it = Y.Ta/phiNsa + Vt/phiVsa;
w('<h2>2. The bar: steel</h2><div class="row"><div><img src="figures/ta_bar.png" alt="bar"></div><div class="calc"><ol>');
w('<li>Tensile stress area of %s (17.6.1.2): A<sub>se</sub> = &pi;/4 (d &minus; 0.9743/n)&sup2; = &pi;/4 (15.875 &minus; 0.9743 &times; 25.4/11)&sup2; = <b>%g mm&sup2;</b> (0.226 in&sup2;).</li>', an.thr, an.Ase);
w('<li>f<sub>uta</sub> = min(f<sub>u</sub>, 1.9 f<sub>ya</sub>, 860) = min(%g, %g, 860) = %g MPa (%s: f<sub>u</sub> 125 ksi, f<sub>y</sub> 105 ksi; elongation 16%%, reduction of area 50%%: ductile, ACI 2.3).</li>', an.futa, 1.9*an.fya, an.futa, an.grade);
w('<li>&phi;N<sub>sa</sub> = 0.75 A<sub>se</sub> f<sub>uta</sub> = 0.75 &times; %g &times; %g = <b>%.1f kN</b> (&phi; = 0.75, ductile steel, Table 17.5.3).</li>', an.Ase, an.futa, phiNsa*kN);
w('<li class="ok">D/C = %.1f / %.1f = %.2f</li>', Y.Ta*kN, phiNsa*kN, Y.Ta/phiNsa);
w('<li>If the end plate holes bore on all four anchors, each top anchor would also take V<sub>u</sub>/4 and half the torsion couple: V<sub>ua</sub> = &radic;[(%.1f/4)&sup2; + (%.1f/2)&sup2;] = %.1f kN; &phi;V<sub>sa</sub> = 0.80 (grout pad) &times; 0.65 &times; 0.6 A<sub>se</sub> f<sub>uta</sub> = %.1f kN.</li>', Y.Vu*kN, Y.Hc*kN, Vt*kN, phiVsa*kN);
w('<li class="ok">Interaction (17.8.3): %.2f + %.2f = %.2f &le; 1.2, D/C %.2f</li>', Y.Ta/phiNsa, Vt/phiVsa, it, it/1.2);
x = row('Thread stripping');
w('<li>Thread stripping of the rod inside one nut (%g high): %s <span class="ok">D/C %.2f</span>.</li>', an.tnut, x{7}, x{4}(1)/x{5}(1));
w('<li>Nuts: hex %s grade 8 (SAE J995) or heavy hex ASTM A194 2H; the nut is stronger than the rod threads. Embedded ends cut flush with the nut (full engagement); at the front, 2 to 3 threads beyond the nut.</li>', an.thr);
w('</ol></div></div>');

% ---- 3. back plate: pullout, then the plate as a beam
Abrg = H.Abrg;  phiNp = 0.70*8*Abrg*fc;  B = R.bpb(1);  K = R.bpk;  Fub = P.st.Fu(bp.grade);
a = bp.w/2 - an.vT;  wq = Y.T/bp.w;  Ra = wq*bp.w/2;
Zg = bp.h*bp.t^2/4;  phiMg = 0.9*Fyb*Zg;  hn = bp.h - an.hole;  phiMn = 0.9*Fyb*hn*bp.t^2/4;
Vpn = 0.6*Fyb*hn*bp.t;  Ko = wq*a^2/2;  Kv = wq*an.vT;  Kred = 1 - (Kv/Vpn)^2;
Bt = ca_bpbeam(P, Y.T, an.hole/2 + 0.5);              % push squeezed against the edge of the hole
% bearing area if only the plate within one thickness of the nut counted
rc = an.dw/2 + bp.t;  yy = linspace(-bp.h/2, bp.h/2, 2001);  Ac = trapz(yy, 2*sqrt(max(rc^2 - yy.^2, 0)));
Ab2 = Ac - pi*an.hole^2/4;  sfb = dc('Side-face blowout');
w('<h2>3. Back plate: bearing on the concrete (pullout)</h2><div class="row"><div><img src="figures/ta_bp.png" alt="back plate"></div><div class="calc"><ol>');
w('<li>Bearing area per anchor: A<sub>brg</sub> = (h b &minus; 2 &pi; d<sub>h</sub>&sup2;/4)/2 = (%g &times; %g &minus; 2 &times; &pi; &times; %g&sup2;/4)/2 = <b>%.0f mm&sup2;</b>.</li>', bp.h, bp.w, an.hole, Abrg);
w('<li>Pullout (17.6.3.2.2a, cracked, &psi;<sub>c,P</sub> = 1): &phi;N<sub>pn</sub> = 0.70 &times; 8 A<sub>brg</sub> f''<sub>c</sub> = 0.70 &times; 8 &times; %.0f &times; %.2f = %.0f kN; <span class="ok">D/C %.2f</span>.</li>', Abrg, fc, phiNp*kN, Y.Ta/phiNp);
w(['<li><b>Where the 8 comes from.</b> Pullout of a headed anchor is the concrete crushing under the head, not a cone. ' ...
   'The concrete under a buried head cannot move sideways (it is surrounded by concrete on all sides), so it carries a bearing pressure many times f''<sub>c</sub> before it crushes: ' ...
   'tests on headed anchors give a mean of roughly 12 to 13 f''<sub>c</sub> in cracked concrete. ACI takes the 5%% fractile, 8 f''<sub>c</sub> (R17.6.3.2.2; Furche 1994, ACI 349). ' ...
   'In uncracked concrete &psi;<sub>c,P</sub> = 1.4 raises it to 11.2 f''<sub>c</sub>. Compare: a bearing plate on the surface of the concrete gets only 0.85 f''<sub>c</sub>, up to 1.7 f''<sub>c</sub> with confinement (22.8.3.2), because the concrete next to it is free.</li>']);
w('<li>Here the pressure under the plate is T<sub>a</sub>/A<sub>brg</sub> = %.1f/%.0f = %.1f MPa = %.2f f''<sub>c</sub>, against 0.70 &times; 8 f''<sub>c</sub> = %.1f MPa.</li>', Y.Ta*kN, Abrg, Y.Ta/Abrg, Y.Ta/Abrg/fc, 0.7*8*fc);
w(['<li>If only the plate within one thickness (t = %g) of the nut counted as bearing area: A<sub>brg</sub> = %.0f mm&sup2;; pullout D/C %.2f, side-face blowout (section 4, &radic;A<sub>brg</sub>) %.2f. ' ...
   'It passes either way; the plate bending checks below show that the plate is strong enough to spread the push over the full area.</li>'], bp.t, Ab2, Y.Ta/(0.7*8*Ab2*fc), sfb(1)*sqrt(Abrg/Ab2));
w('</ol></div></div>');

w('<h2>3b. Back plate: bending and shear</h2>');
w('<div class="row"><div><img src="figures/ta_bpm.png" alt="back plate as a beam"></div><div class="calc"><ol>');
w(['<li><b>The plate as a small beam.</b> The concrete pushes on the whole front face of the plate; the two anchors hold it back through their nuts on the back face. ' ...
   'So the plate works as a beam %g long, on two supports (the anchors, %g apart) with two short overhangs (a = %g). Its cross-section is the plate height times its thickness, %g &times; %g, bending through the thickness.</li>'], bp.w, 2*an.vT, a, bp.h, bp.t);
w('<li>Load: w = T/b = %.0f/%g = <b>%.0f N/mm</b> (uniform: conservative, the real pressure is higher near the anchors). Each anchor pushes back R = w b/2 = %.1f kN.</li>', Y.T, bp.w, wq, Ra*kN);
w(['<li><b>Moment between the anchors</b> (centre, no hole). Half the plate: the nut push R at s/2 = %g from the centre, the concrete load w b/2 with its resultant at b/4 = %g: ' ...
   'M = R s/2 &minus; w (b/2)&sup2;/2 = %.1f &times; %g &minus; %.0f &times; %g&sup2;/2 = <b>%.3f kN m</b>. This needs only where the push is centred, not how the nut spreads it, so it is exact.</li>'], ...
   an.vT, bp.w/4, Ra*kN, an.vT, wq, bp.w/2, B.M0*1e-6);
w(['<li><b>Equation 5, bending capacity</b> (AISC F11, rectangular bar). Fully plastic, half the thickness yields in tension and half in compression: two blocks of F<sub>y</sub> &times; h &times; t/2, %g apart, so ' ...
   'M<sub>p</sub> = F<sub>y</sub> h (t/2)(t/2) = F<sub>y</sub> h t&sup2;/4: Z = %g &times; %g&sup2;/4 = %.0f mm&sup3; (the 1.6 F<sub>y</sub> S cap does not govern: Z/S = 1.5). ' ...
   '&phi;M<sub>p</sub> = 0.9 &times; %g &times; %.0f = %.3f kN m; <span class="ok">D/C %.2f</span> (governs).</li>'], bp.t/2, bp.h, bp.t, Zg, Fyb, Zg, phiMg*1e-6, B.M0/phiMg);
w(['<li><b>Equation 6, shear.</b> The shear next to an anchor is the load that has to travel to it from one side: from the span between the anchors half of it, w s/2 = %.1f kN; from the overhang w a = %.1f kN. ' ...
   'Shear yielding (AISC J4.2a, &phi; = 1.00): 0.6 F<sub>y</sub> h t = 0.6 &times; %g &times; %g &times; %g = %.0f kN on the full width. Through the hole see below.</li>'], Kv*kN, wq*a*kN, Fyb, bp.h, bp.t, 0.6*Fyb*bp.h*bp.t*kN);
w('</ol></div></div>');

w('<h3>The hole: what the first version of this page missed, and why the plate still passes</h3><div class="calc" style="max-width:1100px"><ol>');
w(['<li>The first version put each anchor push at a point on its axis (grey lines in the figure). That gives the largest moment of the overhang, w a&sup2;/2 = %.3f kN m, and the largest shear, %.1f kN, ' ...
   'both exactly at the anchor axis, <b>where the hole is</b>, and it compared them with the full width %g. Through the hole only %g &minus; %g = <b>%g mm</b> are left.</li>'], Ko*1e-6, Kv*kN, bp.h, bp.h, an.hole, hn);
w(['<li>With that model and the net width: &phi;M<sub>p,net</sub> = 0.9 &times; %g &times; %g &times; %g&sup2;/4 = %.3f kN m, D/C %.2f for bending alone. The shear in the same cut, V/V<sub>p,net</sub> = %.1f/%.1f, ' ...
   'leaves (1 &minus; (V/V<sub>p</sub>)&sup2;) = %.2f of the plastic moment (plastic section under moment and shear), so D/C %.2f on paper.</li>'], Fyb, hn, bp.t, phiMn*1e-6, Ko/phiMn, Kv*kN, Vpn*kN, Kred, Ko/(phiMn*Kred));
w(['<li><b>But the nut cannot push on the hole.</b> It presses on the plate over a ring between the hole (&#216;%g) and its bearing face (d<sub>w</sub> = %g, ISO 4032; the washer &#216;%g spreads it further, ignored). ' ...
   'The blue arrows in the figure. Part of the push now acts on the overhang side of the hole and balances the overhang load right there, so the moment at the axis falls from %.3f to %.3f kN m.</li>'], an.hole, an.dw, an.wsh, Ko*1e-6, B.Ma*1e-6);
w(['<li>Worst cut through the hole with the ring: %.1f mm from the centre, width left %.1f, M = %.3f kN m, V = %.1f kN: capacity &phi;M<sub>p,net</sub>(1 &minus; (V/V<sub>p</sub>)&sup2;) = %.3f kN m; <span class="ok">D/C %.2f</span>. ' ...
   'Shear rupture through the hole (J4.2b, &phi; = 0.75): 0.6 F<sub>u</sub> (h &minus; d<sub>h</sub>) t = %.1f kN against %.1f kN; <span class="ok">D/C %.2f</span>.</li>'], ...
   B.xh, B.bh, B.Mh*1e-6, B.Vh*kN, B.Ch*1e-6, B.Mh/B.Ch, B.Cvr*kN, B.Vmx*kN, B.Vmx/B.Cvr);
w(['<li>Not sensitive to the ring: with the whole push squeezed against the edge of the hole (a ring only 0.5 mm wide), the worst cut through the hole is at D/C %.2f. ' ...
   'The cut between the anchors (%.2f) governs in every case, and it has no hole.</li>'], Bt.Mh/Bt.Ch, B.M0/phiMg);
w('<li>Summary, type E: bending between the anchors <b>%.2f</b>; bending + shear through the hole %.2f; shear rupture through the hole %.2f. All types: section 7.</li>', B.M0/phiMg, B.Mh/B.Ch, B.Vmx/B.Cvr);
w('</ol></div>');

% ---- 4. side-face blowout
ca1 = P.col.top - Y.zT;  ca2 = P.col.b/2 - an.vT;  s = 2*an.vT;
Nsb0 = 13*ca1*sqrt(Abrg)*sq;  f2 = 1;  if ca2 < 3*ca1, f2 = (1 + ca2/ca1)/4; end
fg = min(1 + s/(6*ca1), 2);  Nsbg = Nsb0*f2*fg;
w('<h2>4. Side-face blowout towards the top of the pedestal</h2><div class="row"><div><img src="figures/ta_sfb.png" alt="blowout"></div><div class="calc"><ol>');
w(['<li><b>What it is.</b> A deep head close to a free surface pushes the concrete in front of it outwards, sideways, towards that surface, and a body of concrete between the head and the surface spalls off ' ...
   '(red in the figure). It is checked when the head is deep and close to the surface: h<sub>ef</sub> &gt; 2.5 c<sub>a1</sub>. The nearest free surface of this plate is the <b>top of the pedestal</b>.</li>']);
w(['<li><b>The 100.</b> The top of the pedestal is %g mm above the top of the concrete beams (z = 0): the level where the base plate of the steel column sits. ' ...
   'It comes from the site data of the first design (../cantilever_anchor, P.col.top) and is kept in every version; it sets c<sub>a1</sub> and the cover over the back plate. Please confirm it on your column drawings.</li>'], P.col.top);
w('<li>The back plate (anchor axis) is %g below the top of the pedestal: c<sub>a1</sub> = %g &minus; %g = <b>%g</b>. h<sub>ef</sub> = %g &gt; 2.5 c<sub>a1</sub> = %.0f, so 17.6.4.1 applies.</li>', ca1, P.col.top, Y.zT, ca1, bp.u, 2.5*ca1);
w(['<li><b>Size of the spalled body.</b> ACI gives no shape, but its limits imply one: full strength needs 3 c<sub>a1</sub> = %g of concrete to each side of the head (17.6.4.1.1), ' ...
   'and two heads stop acting together at 6 c<sub>a1</sub> apart (17.6.4.2). So the spall reaches about 3 c<sub>a1</sub> from the head on the free surface; drawn so, it is cut by the side faces of the column (c<sub>a2</sub> = %g) ' ...
   'and the two bodies overlap almost completely (s = %g).</li>'], 3*ca1, ca2, s);
w('<li>N<sub>sb</sub> = 13 c<sub>a1</sub> &radic;A<sub>brg</sub> &lambda; &radic;f''<sub>c</sub> = 13 &times; %g &times; &radic;%.0f &times; 1 &times; %.2f = %.1f kN.</li>', ca1, Abrg, sq, Nsb0*kN);
w('<li>Side faces: c<sub>a2</sub> = %g &minus; %g = <b>%g</b> &lt; 3 c<sub>a1</sub> = %g: &times; (1 + c<sub>a2</sub>/c<sub>a1</sub>)/4 = %.3f.</li>', P.col.b/2, an.vT, ca2, 3*ca1, f2);
w('<li>Group of two, s = %g &lt; 6 c<sub>a1</sub> (17.6.4.2): &times; (1 + s/(6 c<sub>a1</sub>)) = %.3f. N<sub>sbg</sub> = %.1f kN.</li>', s, fg, Nsbg*kN);
w('<li class="ok">&phi;N<sub>sbg</sub> = 0.70 &times; %.1f = %.1f kN against T = %.1f kN: D/C %.2f</li>', Nsbg*kN, 0.7*Nsbg*kN, Y.T*kN, Y.T/(0.7*Nsbg));
w('</ol><p class="note">The side faces are free above the beam top (the slab comes later); the top of the pedestal is under the base plate of the steel column. The red body is indicative: the strength comes from the equations, not from the drawing.</p></div></div>');

% ---- 5. anchor reinforcement
ua = H.uc - P.tol.ua;  zat = Y.zT + P.tol.za;
w('<h2>5. Anchor reinforcement: the top bars of the beam in line</h2>');
w('<div class="row"><div><img src="figures/ta_arx.png" alt="section across"></div><div class="calc"><ol>');
w('<li>Tolerances all against the design at once: anchors %g mm high (z = %g), beam bars %g mm low and their hooks %g mm short (ACI 26.6.2.1), back plate %g mm towards the face.</li>', P.tol.za, zat, P.tol.zb, P.tol.ub, P.tol.ua);
w('<li>VCM, lower layer: top line at z = %g, so %g with the tolerance; the 2 bars in contact under the corner bars are not counted (a hooked bundle is outside ACI).</li>', min(P.cb.zt), min(P.cb.zt) - P.tol.zb);
for k = 1:numel(C.vb)
    zbt = C.zb(k) - P.tol.zb;  r_ = min(hypot(C.vb(k) - [-1 1]*an.vT, zbt - zat));
    w('<li>Bar at v = %+g: r = &radic;[(%g &minus; %g)&sup2; + (%g &minus; (%g))&sup2;] = <b>%.1f</b> to the nearest anchor%s.</li>', C.vb(k), abs(C.vb(k)), an.vT, zat, zbt, r_, ifelse(any(C.used == k), '', ' (not counted)'));
end
w('</ol></div></div>');
w('<div class="row"><div><img src="figures/ta_aru.png" alt="section along"></div><div class="calc"><ol>');
w('<li>Breakout body from the bearing face of the back plate (apex u = %g &minus; %g = %g) towards the face, spreading 1.5 across for every 1 along the anchor (the ACI cone: about 35&deg; to the face, 56&deg; to the anchor).</li>', H.uc, P.tol.ua, ua);
for k = C.used
    zbt = C.zb(k) - P.tol.zb;  r_ = min(hypot(C.vb(k) - [-1 1]*an.vT, zbt - zat));  ub = ua - r_/1.5;  uh = C.uh(k) + P.tol.ub;
    w('<li>Bar at v = %+g: the body surface crosses it at u = %g &minus; %.1f/1.5 = %.0f; its hook ends at u = %g + %g = %g; length inside the body %.0f &minus; %g = <b>%.0f</b>.</li>', C.vb(k), ua, r_, ub, C.uh(k), P.tol.ub, uh, ub, uh, ub - uh);
end
psc = min(0.01*fc + 0.6, 1);  l0 = P.fy*psc/(23*sq)*P.cb.db^1.5;
w('<li>Needed inside: the hook development of &#216;12 (25.4.3.1, SI): l<sub>dh</sub> = f<sub>y</sub> &psi;<sub>c</sub> d<sub>b</sub><sup>1.5</sup>/(23 &radic;f''<sub>c</sub>) = %g &times; %.3f &times; 12<sup>1.5</sup>/(23 &times; %.2f) = %.0f, at least max(8 d<sub>b</sub>, 150) = <b>%.0f</b>.</li>', P.fy, psc, sq, l0, H.ldh12);
w('<li class="ok">Shortest inside %.0f &ge; %.0f: D/C %.2f</li>', C.inside, H.ldh12, H.ldh12/C.inside);
w('<li class="ok">Steel: %d bars, &phi;N = 0.75 n A<sub>s</sub> f<sub>y</sub> = 0.75 &times; %d &times; %.0f &times; %g = %.1f kN against T = %.1f kN: D/C %.2f</li>', C.k, C.k, Ab12, P.fy, 0.75*C.k*Ab12*P.fy*kN, Y.T*kN, Y.T/(0.75*C.k*Ab12*P.fy));
w('<li class="ok">Within 0.5 h<sub>ef</sub> of the anchors (R17.5.2.1): farthest counted bar %.0f &le; %.0f, D/C %.2f</li>', C.rmax, 0.5*H.uc, C.rmax/(0.5*H.uc));
w('<li>Beyond the body the bars run into the beam span: l<sub>d</sub> (top bar, &psi;<sub>t</sub> = 1.3) = %.0f mm is available many times over.</li>', H.ld12);
w('</ol></div></div>');

% ---- 6. why not the concrete alone; where the pull goes
w('<h2>6. Why the beam bars are needed, and where the pull goes</h2>');
x = row('Unreinforced breakout');  xs = row('Anchor reinforcement: top bars');
hf = bp.u;  ca1 = P.col.top - Y.zT;  ca2 = P.col.b/2 - an.vT;
phiNfull = 0.70*((ca1 + 1.5*hf)*(2*ca2 + 2*an.vT))/(9*hf^2)*(0.7 + 0.3*min(ca1, ca2)/(1.5*hf))*10*sq*hf^1.5;  xi = row('Anchor reinforcement: beam bars inside');
xa = row('Top anchor, tension + shear');  Tsv = Y.T*(P.etabs.MD + P.etabs.ML)/(Y.Mu/1e6);
w('<div><div><a href="figures/ta_brk.png"><img src="figures/ta_brk.png" alt="breakout" style="width:100%%;max-width:1400px;border:1px solid #ddd"></a></div><div class="calc"><ol>');
w(['<li><b>Stage 1.</b> The plate presses the concrete in front of it towards the face; tension concentrates at the edges of the plate and the first cracks start there, ' ...
   'below the service load (service pull at E about %.0f kN).</li>'], Tsv*kN);
w(['<li><b>Stage 2.</b> The crack reaches the nearest free surface first, the top of the pedestal %g mm above: this is the crack expected in service.</li>'], P.col.top - Y.zT);
w(['<li><b>Stage 3.</b> The crack grows down towards the face and crosses the top bars of the beam in line. From then on the bars, not the concrete, hold the cracked body: ' ...
   'compression from the plate down to the bars (orange), tension in the bars towards the face (blue). Beam bars: steel D/C %.2f; the crossing must have hook length beyond it: D/C %.2f with all tolerances against.</li>'], xs{4}(1)/xs{5}(1), xi{4}(1)/xi{5}(1));
w(['<li><b>Stage 4.</b> The hooks bear against the column ties at the face (<b>contra los estribos</b>). At the ultimate load what gives first is steel: the anchor bar in tension + shear (D/C %.2f) or the beam bars (%.2f), both ductile.</li>'], xa{4}(1)/xa{5}(1), xs{4}(1)/xs{5}(1));
w(['<li><b>After cracking the joint keeps working</b>: the compression path is not cut by the crack, the bars stay elastic in service (about %.0f MPa at E), cracks stay thin, and they end up under the base plate grout and the slab. ' ...
   'It stops working only if the bars are not where the sheets put them (too low, short hooks, hooks away from the ties).</li>'], Tsv/(C.k*pi*P.cb.db^2/4));
w('</ol></div></div>');
Qb = R.brk(1);
w(['<p class="note"><b>What is ACI and what is not.</b> The four stages describe how the crack grows (tests on headed anchors: it starts at the head and grows, reaching the nearest free surface first); ' ...
   'ACI does not describe a sequence. ACI gives one number, the strength of the <b>complete</b> body, up and down at once: projected area A<sub>Nc</sub> = (%g up to the top + 1.5 h''<sub>ef</sub> = %.0f down) &times; %g wide = %.0f mm&sup2;, ' ...
   'with h''<sub>ef</sub> = %.0f because the plate is within 1.5 h<sub>ef</sub> of three edges (17.6.2.1.2, mandatory). &phi;N<sub>cbg</sub> = %.1f kN, D/C %.2f. ' ...
   'Even ignoring that rule and using h<sub>ef</sub> = %g with the body cut only by the edges, &phi;N<sub>cb</sub> &asymp; %.0f kN, D/C %.1f: plain concrete is not enough either way.</p>'], ...
   P.col.top - Y.zT, 1.5*Qb.hefp, P.col.b, Qb.ANc, Qb.hefp, x{5}(1)*kN, x{4}(1)/x{5}(1), bp.u, phiNfull*kN, Y.T/phiNfull);
w('<div class="calc"><ol>');
x = row('Unreinforced breakout');  Q = R.brk(1);
w(['<li>Concrete breakout without reinforcement (17.6.2). The plate is close to three free faces: the top of the pedestal %g above it and the side faces %g to each side, all within 1.5 h<sub>ef</sub>, ' ...
   'so h<sub>ef</sub> is cut to h''<sub>ef</sub> = %.0f (17.6.2.1.2) and the cone is small: &phi;N<sub>cbg</sub> = %.1f kN against T = %.1f kN (D/C %.2f). ' ...
   'A compression from the steel column above would clamp the cone, but ACI does not let it count, and under uplift the top of the pedestal can be in tension. Not relied upon: the pull goes to the beam bars (section 5).</li>'], ...
   P.col.top - Y.zT, P.col.b/2 - an.vT, Q.hefp, x{5}(1)*kN, Y.T*kN, x{4}(1)/x{5}(1));
x = row('Joint shear');  w('<li class="ok">Joint shear (15.4.2.3): %.1f / %.0f kN, D/C %.2f.</li>', x{4}(1)*kN, x{5}(1)*kN, x{4}(1)/x{5}(1));
x = row('Pedestal shear');  w('<li class="ok">Pedestal shear if all of T went into it (22.5): %.1f / %.0f kN, D/C %.2f.</li>', x{4}(1)*kN, x{5}(1)*kN, x{4}(1)/x{5}(1));
x = row('Concrete beam in line');  w('<li class="ok">Beam in line (ETABS B6, with the cantilever, + E<sub>v</sub>): %.1f / %.1f kN m, D/C %.2f.</li>', x{4}(1)*1e-6, x{5}(1)*1e-6, x{4}(1)/x{5}(1));
w('</ol></div>');

% ---- 6b. supplementary U-bar
if P.ub.on
ub = P.ub;  U = R.ub;  zl = P.cb.zt(2);  rB = hypot(an.vT, Y.zT - zl);
xu = row('Supplementary U-bar over');  xd = row('Supplementary U-bar: legs');
cl = @(s) R.clr{find(strncmp(R.clr(:,1), s, numel(s)), 1), 2};
w('<h2>6b. Supplementary U-bar over the top anchors (E, C1, CX)</h2>');
w('<div class="row"><div><img src="figures/ta_ubar.png" alt="U-bar"><img src="figures/ta_ubar3.png" alt="U-bar 3D"></div><div class="calc"><ol>');
w(['<li><b>Why.</b> The pull enters at the anchors (z = %+g) and leaves along the beam top bars (z = %g in the checks): the force line drops %g mm inside the joint. ' ...
   'The compression from the plate down to the bars therefore has a vertical part, and at the plate something must hold it down. ACI''s anchor-reinforcement method leaves that to the concrete in tension, ' ...
   'which is the concrete that cracks (section 6). The U-bar carries it in steel.</li>'], Y.zT, zl, Y.zT - zl);
w(['<li><b>Force, steepest path.</b> All of T going from the plate straight to where the centre bar crosses the breakout body (%g beside the anchor axis, r = %.0f, crossing at u = %g - %.0f/1.5 = %.0f): ' ...
   'V = T &times; %g / %.1f = %.2f T = <b>%.0f kN</b> at E. A flatter path (towards the hooks) gives less: at 25&deg;, the flattest a strut-and-tie model allows (23.2.7), 0.47 T = %.0f kN.</li>'], ...
   an.vT, rB, P.bp.u, rB, P.bp.u - rB/1.5, Y.zT - zl, rB/1.5, U.Vt(1)/Y.T, U.Vt(1)*kN, 0.4663*Y.T*kN);
w(['<li><b>Shape.</b> An upside-down U across the beam (view B): the top rests on both anchors, the two legs go down the joint, and at the bottom each leg turns 90&deg; towards the cantilever face (its hook). ' ...
   'Seen along the beam (view A) the two legs are one behind the other, so it looks like an L; the 3D view C shows the whole bar. The feet can only point towards the face: inwards they would cross, outwards and backwards they would leave the column.</li>']);
w(['<li><b>U-bar.</b> One &#216;%g per beam, standing across the beam at u = %g (7 mm in front of the B1 nuts), its top resting on both A1, legs at v = &plusmn;%g down to z = %g with 90&deg; hooks (tails %g) towards the face. ' ...
   'Two legs: &phi;T = 0.75 &times; 2 &times; %.0f &times; %g = %.0f kN; <span class="ok">D/C %s</span> (E / C1 / CX).</li>'], ...
   ub.db, ub.u, ub.v, ub.zbot, 12*ub.db, pi*ub.db^2/4, P.fy, U.phi*kN, sprintf('%.2f / %.2f / %.2f', xu{4}(1:3)./xu{5}(1:3)));
w(['<li><b>Anchorage.</b> Above the plate: the bend sits on the anchors, which push up on it (bearing, no development needed). Below: hooked development l<sub>dh</sub>(&#216;%g) = %.0f ' ...
   '(&psi;<sub>r</sub> = 1, hooks %g apart &ge; 6 d<sub>b</sub>), available from the bottom of the plate to the outside of the hook %.0f; <span class="ok">D/C %.2f</span>.</li>'], ub.db, U.ldh, 2*ub.v, U.avail(1), xd{4}(1)/xd{5}(1));
w(['<li><b>Clearances</b> (nominal): to the level-A column hooks above %g; legs to the anchors %g, to the VCM corner bars %g (crossing); to the B1 nut %g; to the crossing-beam bars %g; ' ...
   'to the steel column rods %g; hook tails to the joint tie at %g: %g, to the beam bottom bars %g.</li>'], cl('U-bar (resting'), cl('U-bar legs - top'), cl('U-bar legs - VCM'), cl('U-bar - front nut'), ...
   cl('U-bar - grid-4'), cl('U-bar - rods'), min(P.hoop.z), cl('U-bar hook tail - joint'), cl('U-bar hook tail - beam'));
w(['<li><b>The price: the A1 level tolerance.</b> The U-bar rests on the anchors and moves with them, and above it there are only %g mm to the level-A column hooks. ' ...
   'With the U-bar the anchors may be at most about 5 mm high (not the +15 of the sheets); without it, +15 stands. CY gets no U-bar: its anchors at %+g are right under the column hooks.</li>'], cl('U-bar (resting'), R.typ(4).zT);
w(['<li><b>Status.</b> Supplementary: it does not change any ACI check above (the anchor-reinforcement method does not count it). It makes the strut-and-tie model of the joint complete, with steel at the plate, ' ...
   'and it keeps the top crack thin. Placed after the A1 + B1 assembly, before the column hooks are bent.</li>']);
w('</ol></div></div>');
else
% the U-bar was dropped (user 2026-10-03): the level-A column hooks are the vertical tie at the plate
zl = P.cb.zt(2);  rc = P.col.cover + P.col.dtie + P.col.db/2;  zhA = P.col.top - P.col.ctop - P.col.db/2;
rB = hypot(an.vT, Y.zT - zl);  Vt = Y.T*(Y.zT - zl)/(rB/1.5);  phiC = 0.75*2*pi*P.col.db^2/4*P.fy;
w('<h2>6b. Vertical tie at the back plate: the level-A column hooks</h2><div class="calc" style="max-width:1150px"><ol>');
w(['<li><b>Why.</b> The pull enters at the anchors (z = %+g) and leaves along the beam top bars (z = %g in the checks): the force line drops %g mm inside the joint. ' ...
   'The compression from the plate down to the bars (orange in figure G) has a vertical part, and at the plate something must hold it down. ' ...
   'ACI''s anchor-reinforcement method leaves that to the concrete; it is not a required check.</li>'], Y.zT, zl, Y.zT - zl);
w(['<li><b>Force, steepest path.</b> All of T from the plate straight to where the centre bar crosses the breakout body (r = %.0f, u = %.0f): ' ...
   'V = T &times; %g / %.1f = %.2f T = <b>%.0f kN</b> at E; a flatter path gives less.</li>'], rB, P.bp.u - rB/1.5, Y.zT - zl, rB/1.5, Vt/Y.T, Vt*kN);
w(['<li><b>What holds it: the far-face bars of the column</b> (u = %g), vertical and continuous down the column, straight up to z = %+g; above it they bend into ' ...
   'their level-A hooks along the anchors (z = %+g). B1 (face at u = %g) bears on the back leg of the closed tie &#216;%g under the anchors (z = %+g, right under the B1 front nuts), and the tie on these bars ' ...
   '(user 2026-10-05). Two &#216;%g: 0.75 &times; 2 &times; %.0f &times; %g = %.0f kN against %.0f kN. Not counted in any check: these bars are also the pedestal bars of the steel column.</li>'], ...
   P.col.b - rc, zhA - 3.5*P.col.db, zhA, P.bp.u, P.top.db, P.top.zu, P.col.db, pi*P.col.db^2/4, P.fy, phiC*kN, Vt*kN);
w(['<li><b>The hooks.</b> Level A (z = %+g, top cover %g; ACI Table 20.5.1.3.1 asks 40, the user takes %g under the base plate grout and the slab): the corners and the front and far ' ...
   'mid bars, along the anchors. Level B (z = %+g): the two side mid bars, across, resting on the A1. With the A1 %g mm high, level B rides up; level A still clears it (cover %g). ' ...
   'Was: level A across, resting on the B1 nuts; level B along the A1 at +29.</li>'], zhA, P.col.ctop, P.col.ctop, P.col.zhB, P.tol.za, P.col.cmin);
w(['<li><b>CY (D4):</b> its anchors are at %+g, resting on those of X. Same arrangement, oriented by X: level A along the anchors of X (east-west), level B (north and south mid bars) ' ...
   'across, on the anchors of X, beside those of Y. The closed tie &#216;%g over the anchors goes at z = %+g, over the front nuts of the Y back plate ' ...
   '(%+g elsewhere). The two ties &#216;%g at %+g and %+g are under the anchors, both within 127 of the top (ACI 10.7.6.1.5).</li>'], ...
   R.typ(4).zT, P.t10.db, P.t10.zD4, P.t10.z, P.top.db, P.top.z);
w(['<li><b>The U-bar</b> (one &#216;16 across the beam in front of B1, legs down the joint) was dropped: it did not fit at CX against the grid-D bottom hooks, ' ...
   'it cut the A1 level tolerance to about +5, and the corner hooks above do the same work.</li>']);
w('</ol></div>');
end

% ---- 6c. stress test: hooked anchors
h = R.hka;  T4 = [R.typ.T];  f4 = @(v) sprintf('%.2f / %.2f / %.2f / %.2f', v);  g4 = @(v) sprintf('%.1f / %.1f / %.1f / %.1f', v*kN);
w('<h2>6c. Stress test: the bars crossing the crack counted as hooked anchors</h2><div class="calc" style="max-width:1150px"><ol>');
w(['<li><b>What changes.</b> Sections 5 and 6 treat the beam bars as reinforcement developed by chapter 25 (bond along the bar plus the hook). Here each bar is treated as a hooked anchor (17.6.3.2.2b): ' ...
   'only the bearing inside its hook counts, no bond, e<sub>h</sub> at most 4.5 d<sub>b</sub>, cracked concrete: &phi;N<sub>p</sub> = 0.70 &times; 0.9 f''<sub>c</sub> e<sub>h</sub> d<sub>b</sub> = ' ...
   '<b>%.1f kN</b> per &#216;12, <b>%.1f kN</b> per &#216;14 tie leg, %.1f kN per &#216;10 tie leg. ACI does not ask for this; it is the most pessimistic reading of the same bars.</li>'], h.one/1e3);
w(['<li><b>Which bars.</b> Only bars parallel to the anchors, within 0.5 h<sub>ef</sub> = %.0f of an anchor (anchors %g mm high), with their hook inside the breakout body (at the cantilever face): ' ...
   'the beam top bars (%d / %d / %d / %d); the 2 extra beam bars at %g where they are not in contact with the corner bars (C4 and D4-south); ' ...
   'the side legs of the two closed ties &#216;14 (at %g and %g, %.0f to %.0f from an anchor, held at the face by the tie corner around the corner column bar). ' ...
   'The joint tie &#216;10 at %g is %.0f away: outside 0.5 h<sub>ef</sub>, not counted.</li>'], 0.5*H.uc, P.tol.za, h.kb, P.cb.zp, P.top.z(2), P.top.z(1), min(h.r14(:)), max(h.r14(:)), max(P.hoop.z), h.r10(1));
w('</ol></div>');
% ---- 6d. shear across z = 0 (user 2026-10-05)
Avf = P.ub2.n*2*pi*P.ub2.db^2/4;  phiU = 0.75*1.4*Avf*P.fy;  Avr = 4*pi*P.rod.db^2/4;  phiRd = 0.75*1.4*Avr*P.fy;
phiPl = 0.6*0.11*sqrt(P.fc)*P.col.b^2;
w('<h2>6d. Shear across z = 0: the pedestal block above the beams</h2>');
w('<div><div><img src="figures/ta_z0.png" alt="shear across z = 0" style="width:100%%;max-width:1400px;border:1px solid #ddd"></div><div class="calc"><ol>');
w(['<li><b>What.</b> B1 sits in the top %g mm of the pedestal, above the beams. The pull T pushes that block towards the cantilever and it must pass T down into the joint across the horizontal plane at z = 0. ' ...
   'This is not the 45&deg; diagonal tension of the joint (the joint ties and the joint shear check): it is direct shear transfer along a plane, ACI 318-19 22.9 (shear friction). There is no cold joint there; the plane is monolithic.</li>'], P.col.top);
w(['<li><b>Which bars count.</b> Only vertical bars crossing the plane and developed for f<sub>y</sub> on <b>both</b> sides (318-11 11.6.8; 318-19 22.9). ' ...
   'The column bars end in their hooks about 90 mm above the plane (l<sub>dh</sub> about 205): not developed above, and 25.4.10.2(b) does not allow counting them at a reduced stress. ' ...
   'The 4 rods of the steel column are developed both sides (hooks more than 1 m below; base plate and nut above): A<sub>vf</sub> = %.0f mm&sup2;, &phi;V<sub>n</sub> = 0.75 (1.4) A<sub>vf</sub> f<sub>y</sub> = <b>%.0f kN</b>, if the column is mounted and tightened before the cantilever is loaded.</li>'], Avr, phiRd/1e3);
w(['<li><b>Demand.</b> T = %.0f / %.0f / %.0f / %.0f kN (E / C1 / CX / CY; at D4 X and Y add as vectors). Plain concrete only (14.5.5.1, &phi; = 0.6, 400 x 400): %.0f kN, not enough at E.</li>'], [R.typ.T]/1e3, phiPl/1e3);
w(['<li><b>Alternative without relying on the steel column: %d hairpins &#216;%g</b> (figure, orange): legs at v = &plusmn;%g, u = %g, crown over the A1, 90&deg; hooks under the beam bars: ' ...
   '&phi;V<sub>n</sub> = %.0f kN (D/C %.2f at E).</li>'], P.ub2.n, P.ub2.db, P.ub2.v, P.ub2.u, phiU/1e3, R.typ(1).T/phiU);
w('</ol></div></div>');
% joint ties Ø10: previous and new levels against the 35 deg cone
w('<h3>Joint ties &#216;10: previous and new levels (user 2026-10-04: spread for the pour)</h3><div class="calc" style="max-width:1150px"><p>');
w(['Only the side legs of a tie run parallel to the anchors (at v = &plusmn;%g). A leg counts if it is within 0.5 h<sub>ef</sub> = %.1f of an anchor (R17.5.2.1); ' ...
   'the breakout surface is the ACI one, at <b>35&#176; to the cantilever face</b> (R17.6.2.1, Fig. R17.6.2.1: about 35&#176;; the 1.5 h<sub>ef</sub> projection is 33.7&#176;): ' ...
   'a leg at a distance r from the anchor axis crosses it at u = %g &minus; r tan 35&#176;, with the front corner of the tie (u = %g) inside the body. ' ...
   'r = &radic;((%g &minus; %g)&sup2; + (z<sub>A</sub> &minus; z)&sup2;), z<sub>A</sub> = %+g nominal, %+g with the anchors %g high. ' ...
   'So a layer counts only above z = %.1f (nominal) or %.1f (anchors high).</p></div>'], ...
   P.col.b/2 - P.col.cover - P.hoop.db/2, 0.5*H.uc, H.uc, P.col.cover + P.hoop.db/2, P.col.b/2 - P.col.cover - P.hoop.db/2, an.vT, Y.zT, Y.zT + P.tol.za, P.tol.za, h.zlim);
w('<div class="tw"><table><tr><th>Layout</th><th>z</th><th>r nominal</th><th>r, anchors high</th><th>crosses the surface at u (35&#176;)</th><th>counted (nominal / high)</th></tr>');
lab = {'previous', 'new'};
for k = 1:2
    L = h.lay(k);
    for i = 1:numel(L.z)
        w('<tr><td>%s</td><td>%g</td><td>%.1f</td><td>%.1f</td><td>%.0f</td><td>%s / %s</td></tr>', lab{k}, L.z(i), L.rn(i), L.rt(i), L.ucn(i), ifelse(L.in_n(i), 'yes', 'no'), ifelse(L.in_t(i), 'yes', 'no'));
    end
end
w('</table></div><div class="calc" style="max-width:1150px"><p><b>What the new layout loses: nothing.</b> The top layer stays at %g (counted only with the anchors at their nominal level, %.1f against %.1f); ' ...
  , max(P.hoop.z), h.lay(2).rn(1), 0.5*H.uc);
w('the other three layers were never within 0.5 h<sub>ef</sub> (they are 200 to 300 mm from the anchors), in either layout. The stress-test sums above do not count any &#216;10 leg.</p></div>');
% side by side: the two ways to check the same Ø12 beam bar
db12 = P.cb.db;  Ab12b = pi*db12^2/4;  psc = min(0.01*fc + 0.6, 1);  ldh = H.ldh12;
ldh0 = P.fy*psc/(23*sq)*db12^1.5;  xi = row('Anchor reinforcement: beam bars inside');  xs = row('Anchor reinforcement: top bars');
w('<h3>The same &#216;12 bar, two sets of equations</h3><div class="tw"><table><tr><th></th><th>Developed reinforcement (what the design uses)</th><th>Hooked anchor (stress test)</th></tr>');
w('<tr><td>ACI clause</td><td>17.5.2.1(a) sends anchor reinforcement to chapter 25: hooked bar development 25.4.3</td><td>17.6.3.2.2(b), pullout of a hooked bolt (J or L bolt)</td></tr>');
w('<tr><td>Mechanism</td><td>bond along the deformed bar + bearing in the hook + the ties around it</td><td>bearing inside the hook only; no bond, no friction</td></tr>');
w(['<tr><td>Equation</td><td>l<sub>dh</sub> = f<sub>y</sub> &psi;<sub>e</sub> &psi;<sub>r</sub> &psi;<sub>o</sub> &psi;<sub>c</sub> d<sub>b</sub><sup>1.5</sup> / (23 &lambda; &radic;f''<sub>c</sub>) &ge; max(8 d<sub>b</sub>, 150); ' ...
   'if the bar has l<sub>dh</sub> beyond the crack it carries &phi; A<sub>s</sub> f<sub>y</sub></td><td>N<sub>p</sub> = 0.9 f''<sub>c</sub> e<sub>h</sub> d<sub>a</sub>, e<sub>h</sub> &le; 4.5 d<sub>a</sub>; &phi;N<sub>p</sub>, &psi;<sub>c,P</sub> = 1.0 cracked</td></tr>']);
w(['<tr><td>Our numbers</td><td>l<sub>dh</sub> = %g &times; %.3f &times; %g<sup>1.5</sup> / (23 &times; %.2f) = %.0f &rarr; %.0f (minimum); available %.0f (all tolerances against): developed. ' ...
   '&phi;A<sub>s</sub> f<sub>y</sub> = 0.75 &times; %.0f &times; %g = <b>%.1f kN</b> per bar</td><td>e<sub>h</sub> = 4.5 &times; %g = %g; &phi;N<sub>p</sub> = 0.70 &times; 0.9 &times; %.2f &times; %g &times; %g = <b>%.1f kN</b> per bar</td></tr>'], ...
   P.fy, psc, db12, sq, ldh0, ldh, xi{5}(1), Ab12b, P.fy, 0.75*Ab12b*P.fy*kN, db12, 4.5*db12, fc, 4.5*db12, db12, h.one(1)/1e3);
w('<tr><td>Calibrated on</td><td>deformed bars in reinforced concrete members and joints, cracked</td><td>tests on smooth hooked bolts with short embedment, which straighten and slip</td></tr>');
w('<tr><td>Applies to</td><td>reinforcement, including anchor reinforcement (17.5.2.1, 23.8.3 for ties in strut-and-tie)</td><td>anchors: a hooked bolt whose force must come out of the concrete around its hook</td></tr>');
w('<tr><td>Result, type E (top line)</td><td class="ok">D/C %.2f (steel), %.2f (development, tolerances)</td><td class="ng">D/C %.2f (bars alone); %.2f with the &#216;14 tie legs</td></tr>', ...
   xs{4}(1)/xs{5}(1), xi{4}(1)/xi{5}(1), T4(1)/h.Nb(1), T4(1)/(h.Nb(1) + h.Np(1) + h.N14(1)));
w('</table></div>');
w('<div class="calc" style="max-width:1150px"><p><b>Which one applies.</b> The code decides it: 17.5.2.1(a) requires anchor reinforcement to be developed <i>in accordance with chapter 25</i>, so the beam bars are checked as developed reinforcement. ');
w('The hooked-bolt equation belongs to anchors (17.1.2b, hooked bolts), and the beam bars are not anchors. Three independent cross-checks point the same way: ');
w('(1) the beam design already relies on the same hooks to develop the beam''s own tension at this column face, about 47 kN per bar, by chapter 25; using 8 kN for the same hook here would be inconsistent; ');
w('(2) a strut-and-tie model of the joint anchors its ties by chapter 25 too (23.8.3); (3) Eurocode EN 1992-4 checks anchor (supplementary) reinforcement with its bond anchorage length inside the cone, also a development check, not a hook-bearing one (quoted from memory). ');
w('The hooked-anchor reading is kept as a stress test: it ignores bond, which is real, and it still passes once the existing &#216;14 ties are counted.</p></div>');
w('<div class="tw"><table><tr><th>Counted as hooked anchors</th><th class="n">E</th><th class="n">C1</th><th class="n">CX</th><th class="n">CY</th></tr>');
w('<tr><td>T on the two anchors (kN)</td><td class="n">%s</td></tr>', strrep(g4(T4), ' / ', '</td><td class="n">'));
rowsT = {'Beam top bars only', h.Nb; '+ the 2 extra beam bars (C4, D4-south)', h.Nb + h.Np; ...
         '+ the side legs of the 2 closed ties &#216;14 (existing)', h.Nb + h.Np + h.N14; ...
         '+ a third closed tie &#216;14 at -41 (proposed)', h.Nb + h.Np + h.N14 + h.N41};
for i = 1:size(rowsT, 1)
    v = rowsT{i,2};  dcv = T4./v;  cls = repmat({'n'}, 1, 4);
    w('<tr><td>%s</td>', rowsT{i,1});
    for j = 1:4, w('<td class="n %s">%.1f kN, D/C %.2f</td>', ifelse(dcv(j) <= 1, 'ok', 'ng'), v(j)*kN, dcv(j)); end
    w('</tr>');
end
w('</table></div><div class="calc" style="max-width:1150px"><ol start="3">');
w(['<li><b>Reading.</b> The beam bars alone, as hooked anchors, hold about a third of the pull: that is what the RAM anchors suffered from. The steel that already exists, beam bars plus the two closed ties &#216;14, ' ...
   'carries all of it even in this reading (worst %.2f at E). A third closed tie &#216;14 directly under the one at -25 (at -41, between it and the beam top bars, 2 mm clear each side) brings the worst case to %.2f.</li>'], ...
   max(T4./(h.Nb + h.Np + h.N14)), max(T4./(h.Nb + h.Np + h.N14 + h.N41)));
w('</ol></div>');

% ---- 7. four types
w('<h2>7. The four types</h2><div class="tw"><table><tr><th></th>');
for j = 1:4, w('<th>%s</th>', R.typ(j).name); end
w('</tr>');
lst = {'T (kN)', [R.typ.T]*kN, '%.1f'; 'T<sub>a</sub> (kN)', [R.typ.Ta]*kN, '%.1f'; 'z of the anchors', [R.typ.zT], '%+g';
       'Bar steel', dc('Top anchor, steel'), '%.2f'; 'Tension + shear', dc('Top anchor, tension + shear'), '%.2f';
       'Pullout', dc('Pullout at the back plate'), '%.2f'; 'Side-face blowout', dc('Side-face blowout'), '%.2f';
       'Back plate bending, between the anchors', dc('Back plate bending between'), '%.2f';
       'Back plate through the hole', dc('Back plate through the hole'), '%.2f'; 'Beam bars counted', [R.cone.k], '%d';
       'Anchor reinforcement, steel', dc('Anchor reinforcement: top bars'), '%.2f';
       'Anchor reinforcement, inside the body', dc('Anchor reinforcement: beam bars inside'), '%.2f';
       'Within 0.5 h<sub>ef</sub>', dc('Anchor reinforcement within'), '%.2f'};
if P.ub.on, lst(end+1,:) = {'U-bar, vertical tie (not at CY)', dc('Supplementary U-bar over'), '%.2f'}; end
for k = 1:size(lst,1)
    w('<tr><td>%s</td>', lst{k,1});
    for j = 1:4, w(['<td>' lst{k,3} '</td>'], lst{k,2}(j)); end
    w('</tr>');
end
w('</table></div><p class="note">CY: anchors at z = %+g, so c<sub>a1</sub> = %g for the blowout. Corner beams counted as VCS on their bar layer (CY on the upper layer by the corner rule).</p>', R.typ(4).zT, P.col.top - R.typ(4).zT);
% ---- 8. shear anchors: the concrete side
S = R.shc;  Vv = [R.typ.Vu];  Hv = [R.typ.Hc];  Vs = Vv(1);  Hs = Hv(1);  x = row('Shear anchor, steel');
w('<h2>8. Shear anchors A2: shear on the concrete side</h2>');
w(['<p>Two concrete failures exist in shear, and only one of them is a cone. <b>Pryout</b> (17.7.3) is the tension cone again: the stubby anchor levers about the concrete it bears on at the face, its end nut lifts, and it pulls a cone out behind it, so its strength is k<sub>cp</sub> N<sub>cb</sub>. ' ...
   '<b>Shear breakout</b> (17.7.2) is a different body: a half cone pushed out towards the free edge the shear points at. It depends on the distance to that edge, c<sub>a1</sub>, and hardly on h<sub>ef</sub> (only through l<sub>e</sub>). ' ...
   'The first version of the calculation had steel and pryout, and dismissed breakout because V points down where the column goes on. It missed two things: the torsion couple H pushes the shear anchors across the beam, towards a free side face, and ACI also checks a shear that runs <i>parallel</i> to an edge (17.7.2.1(c)). Both are below.</p>']);
w('<div class="row"><div><img src="figures/ta_spry.png" alt="pryout"></div><div class="calc"><ol>');
w('<li>Forces on the two shear anchors (type E): V<sub>u</sub> = <b>%.1f kN</b> down; torsion T<sub>u</sub> = %.2f kN m makes a horizontal couple with the top anchors, H = T<sub>u</sub>/(z<sub>A1</sub> &minus; z<sub>A2</sub>) = %.2f/(%.3f) = <b>%.1f kN</b> across, either way.</li>', ...
  Vs*kN, R.typ(1).Tor*1e-6, R.typ(1).Tor*1e-6, (R.typ(1).zT - S.zS)/1e3, Hs*kN);
w('<li>Up: the uplift combination 0.9D &minus; E<sub>v</sub> still leaves q = %.2f kN/m&sup2; down, so V never points to the top of the pedestal. Down: the column goes on below the cold joint (not a free edge), so no breakout downward.</li>', R.q(3));
w('<li>Pryout body (figure I): 1.5 h<sub>ef</sub> = %g from the axes at the face. Across: %g + 2 &times; min(c<sub>a</sub> = %g, %g) = %.0f; up and down: min(%.0f, %g) + %g = %.0f. A<sub>Nc</sub> = %.0f &times; %.0f = %.0f mm&sup2;, A<sub>Nco</sub> = 9 h<sub>ef</sub>&sup2; = %.0f mm&sup2;.</li>', ...
  1.5*S.hef, 2*an.vS, P.col.b/2 - an.vS, 1.5*S.hef, 2*min(P.col.b/2 - an.vS, 1.5*S.hef) + 2*an.vS, S.ctop, 1.5*S.hef, 1.5*S.hef, min(S.ctop, 1.5*S.hef) + 1.5*S.hef, ...
  2*min(P.col.b/2 - an.vS, 1.5*S.hef) + 2*an.vS, min(S.ctop, 1.5*S.hef) + 1.5*S.hef, S.ANc, S.ANco);
w('<li>N<sub>b</sub> = k<sub>c</sub> &lambda; &radic;f''<sub>c</sub> h<sub>ef</sub><sup>1.5</sup> = 10 &times; %.2f &times; %g<sup>1.5</sup> = %.1f kN (cast-in, k<sub>c</sub> = 10; cracked, &psi;<sub>c,N</sub> = 1); &psi;<sub>ed,N</sub> = %.2f (c<sub>a,min</sub> = %g &ge; 1.5 h<sub>ef</sub>); &psi;<sub>ec,N</sub> = 1.</li>', sq, S.hef, S.Nb*kN, S.pedN, P.col.b/2 - an.vS);
w('<li>N<sub>cbg</sub> = (%.0f/%.0f) &times; %.2f &times; %.1f = %.1f kN; &phi;V<sub>cpg</sub> = 0.70 &times; k<sub>cp</sub> N<sub>cbg</sub> = 0.70 &times; 2 &times; %.1f = <b>%.1f kN</b> (k<sub>cp</sub> = 2 for h<sub>ef</sub> &ge; 65).</li>', S.ANc, S.ANco, S.pedN, S.Nb*kN, S.Ncbg*kN, S.Ncbg*kN, S.phiVcp*kN);
w('<li class="ok">V on the group &radic;(V&sup2; + H&sup2;) = %.1f kN; D/C %.2f</li>', S.Vg(1)*kN, S.Vg(1)/S.phiVcp);
w('<li>The lower edge of the body reaches the cold joint at %g (1 mm past it). A cold joint is not an edge: the column below is the same member, tied through by the column bars. The end-plate compression of the moment (C = T, near the bottom flange) presses on this body; ACI does not count it.</li>', P.col.cj);
w('</ol></div></div>');
w('<div class="row"><div><img src="figures/ta_sbrk.png" alt="breakout plan"></div><div class="calc"><ol start="8">');
w(['<li><b>Breakout towards a side face</b> (figure J). The holes in the end plate are not welded to the anchors, so ACI gives two readings (R17.7.2.1, Fig. R17.7.2.1b): ' ...
   '<b>case 1</b>, the near anchor takes its half and breaks out at c<sub>a1</sub> = %g; <b>case 2</b>, the near anchor has slipped or broken out and the far one takes all, at c<sub>a1</sub> = %g.</li>'], S.ca1(1), S.ca1(2));
w('<li>Basic strength (17.7.2.2.1): V<sub>b</sub> = min[0.6 (l<sub>e</sub>/d<sub>a</sub>)<sup>0.2</sup> &radic;d<sub>a</sub> &lambda; &radic;f''<sub>c</sub> c<sub>a1</sub><sup>1.5</sup>, 3.7 &lambda; &radic;f''<sub>c</sub> c<sub>a1</sub><sup>1.5</sup>], l<sub>e</sub> = h<sub>ef</sub> = %g &le; 8 d<sub>a</sub> = %g, d<sub>a</sub> = %g. Case 1: %.1f kN; case 2: %.1f kN.</li>', S.le, 8*an.db, an.db, S.Vb(1)*kN, S.Vb(2)*kN);
for i = 1:2
    r = 1.5*S.ca1(i);
    w(['<li>Case %d, c<sub>a1</sub> = %g, 1.5 c<sub>a1</sub> = %.0f. A<sub>Vc</sub> on the side face = [min(%.0f to the top, %.0f) + %.0f down the column] &times; min(h<sub>a</sub> = %g, %.0f) = %.0f mm&sup2;; A<sub>Vco</sub> = 4.5 c<sub>a1</sub>&sup2; = %.0f mm&sup2;. ' ...
       '&psi;<sub>ed,V</sub> = %.2f, &psi;<sub>c,V</sub> = 1.0 (cracked, edge bars not counted), &psi;<sub>h,V</sub> = %.2f. V<sub>cb</sub> = %.3f &times; %.2f &times; %.1f = %.1f kN; &phi; = 0.70: <b>%.1f kN</b> perpendicular to the edge, and <b>%.1f kN</b> parallel to it (2 &times; with &psi;<sub>ed,V</sub> = 1, 17.7.2.1(c)).</li>'], ...
      i, S.ca1(i), r, S.ctop, r, r, S.ha, r, S.Avc(i), S.Avco(i), S.pedV(i), S.ph(i), S.Avc(i)/S.Avco(i), S.pedV(i), S.Vb(i)*kN, S.Vcb(i)*kN, S.phiVb(i)*kN, S.phiVp(i)*kN);
end
w('</ol></div></div>');
w('<div class="row"><div><img src="figures/ta_sfr.png" alt="face"></div><div class="calc"><ol start="12">');
w(['<li><b>The two components together.</b> H is perpendicular to the side face, V is parallel to it. ACI checks each one alone: case 1, H/2 = %.1f against %.1f kN (%.2f) and V/2 = %.1f against %.1f kN (%.2f); case 2, H = %.1f against %.1f kN (%.2f) and V = %.1f against %.1f kN (%.2f). ' ...
   'ACI has no rule for a shear inclined to the edge; EN 1992-4 (7.2.2.5, &psi;<sub>&alpha;,V</sub>) combines them as V<sub>res</sub>/V<sub>cb,&alpha;</sub> = &radic;[(V<sub>&perp;</sub>/V<sub>cb</sub>)&sup2; + (V<sub>&#8741;</sub>/2V<sub>cb</sub>)&sup2;], which is what the calc uses.</li>'], ...
   Hs/2*kN, S.phiVb(1)*kN, Hs/2/S.phiVb(1), Vs/2*kN, S.phiVp(1)*kN, Vs/2/S.phiVp(1), Hs*kN, S.phiVb(2)*kN, Hs/S.phiVb(2), Vs*kN, S.phiVp(2)*kN, Vs/S.phiVp(2));
w('<li class="ok">Case 1: &radic;(%.2f&sup2; + %.2f&sup2;) = %.2f. Case 2: &radic;(%.2f&sup2; + %.2f&sup2;) = %.2f, governs.</li>', Hs/2/S.phiVb(1), Vs/2/S.phiVp(1), sqrt(S.ell1(1)), Hs/S.phiVb(2), Vs/S.phiVp(2), sqrt(S.ell2(1)));
w('<li>Figure K shows the bodies on the face of the cantilever: the pryout area A<sub>Nc</sub> (blue), and where each breakout half cone comes out on this face (red, orange). The orange one is cut by the top of the pedestal, hence &psi;<sub>ed,V</sub> &lt; 1 in case 2.</li>');
w('<li>Reserve not used: the &#216;16 column bars between the anchors and the side face would allow &psi;<sub>c,V</sub> = 1.2 (Table 17.7.2.5.1); the concrete beams that frame into some side faces make them not free at all.</li>');
w(['<li><b>Relation to the cone of the top anchors</b> (section 6): that body opens from the back plate at u = %g towards the face around z = %+g. The pryout body of the shear anchors sits near the face below z = %.0f, under the beam top bars. ' ...
   'ACI checks them separately; physically the end-plate compression (C = T) bears on the face over the pryout body, which helps it.</li>'], bp.u, Y.zT, S.zS + 1.5*S.hef);
w('</ol></div></div>');
w('<div class="tw"><table><tr><th></th>');
for j = 1:4, w('<th>%s</th>', R.typ(j).name); end
w('</tr>');
lst = {'V<sub>u</sub> down (kN)', Vv*kN, '%.1f'; 'H across (kN)', Hv*kN, '%.1f'; 'Steel, per anchor (grout pad)', x{4}./x{5}, '%.2f';
       'Pryout of the group', dc('Pryout of the 2 shear'), '%.2f'; 'Breakout to a side face, case 1', dc('Shear breakout of the shear anchors towards a side face, case 1'), '%.2f';
       'Breakout to a side face, case 2', dc('Shear breakout of the shear anchors towards a side face, case 2'), '%.2f'};
for k = 1:size(lst,1)
    w('<tr><td>%s</td>', lst{k,1});
    for j = 1:4, w(['<td>' lst{k,3} '</td>'], lst{k,2}(j)); end
    w('</tr>');
end
w('</table></div>');
% ---- 8b. top anchors in shear
St = R.sht;  j4 = 4;  Y4 = R.typ(j4);
w('<h2>8b. Top anchors A1 in shear</h2>');
w(['<p><b>Which way the shear goes decides where the cone is.</b> A shear breakout opens towards the free face the shear points at. V points down: below the top anchors there are %.0f mm of concrete to the shear anchors and the whole column after them, so there is no cone downward. ' ...
   'The %g mm of concrete above them (%g at CY) is on the side <i>away</i> from V. That is where a pryout crater would open, and pryout is checked with the cone cut by the top. ' ...
   'The shear that does point at a free face is the torsion couple H, across the beam towards a side face, and the top of the pedestal cuts that half cone (figure L).</p>'], Y.zT - S.zS, P.col.top - Y.zT, P.col.top - R.typ(4).zT);
w(['<p><b>What the top anchors carry.</b> The calculation gives V to the shear anchors (they are designed for all of it). The top anchors always carry H: it is half of the torsion couple, and it cannot move to the shear anchors. ' ...
   'If the four holes of the end plate bore at once, each top anchor would also take V/4. That is checked too, as information.</p>']);
w('<div class="row"><div><img src="figures/ta_stop.png" alt="top anchors shear"></div><div class="calc"><ol>');
w(['<li>Breakout to a side face, as for the shear anchors (17.7.2, cases 1 and 2), now with the top of the pedestal at c<sub>a2</sub> = %g (CY): l<sub>e</sub> = min(h<sub>ef</sub>, 8 d<sub>a</sub>) = %g. ' ...
   'Case 1 (c<sub>a1</sub> = %g): A<sub>Vc</sub> = (%g + %.0f) &times; %.0f = %.0f mm&sup2; of A<sub>Vco</sub> = %.0f, &psi;<sub>ed,V</sub> = %.2f: &phi;V<sub>cb</sub> = <b>%.1f kN</b> across, %.1f kN parallel. ' ...
   'Case 2 (c<sub>a1</sub> = %g): A<sub>Vc</sub>/A<sub>Vco</sub> = %.2f, &psi;<sub>ed,V</sub> = %.2f: &phi;V<sub>cb</sub> = <b>%.1f kN</b> across, %.1f kN parallel.</li>'], ...
   St.ctop(j4), St.le, St.ca1(1), St.ctop(j4), 1.5*St.ca1(1), 1.5*St.ca1(1), St.Avc(1,j4), St.Avco(1,j4), St.pedV(1,j4), St.phiVb(1,j4)*kN, St.phiVp(1,j4)*kN, ...
   St.ca1(2), St.Avc(2,j4)/St.Avco(2,j4), St.pedV(2,j4), St.phiVb(2,j4)*kN, St.phiVp(2,j4)*kN);
w('<li>Pryout of the pair (17.7.3): &phi;V<sub>cpg</sub> = 0.70 &times; 2 N<sub>cbg</sub> with the unreinforced cone of section 6 (h''<sub>ef</sub> = %.0f, cut by the top and both sides): %.1f kN (CY), %.1f kN (E).</li>', R.brk(j4).hefp, St.phiVcp(j4)*kN, St.phiVcp(1)*kN);
w('<li>H on the pair at CY: %.1f kN. Shear ratios with H alone: case 1 %.2f, case 2 <b>%.2f</b>, pryout %.2f, steel %.2f.</li>', Y4.Hc*kN, St.b1(1,j4), St.b2(1,j4), St.cp(1,j4), St.sa(1,j4));
[~, jw] = max(St.int(1,:));
w(['<li><b>Tension + shear (17.8.3).</b> The same anchors pull T. Tension ratio: the largest of bar steel, pullout, blowout and the anchor reinforcement. For the reinforcement it is the steel of every beam bar still developed inside the body (CY: %d bars, %.2f). ' ...
   'Both ratios are over 0.2, so N/&phi;N<sub>n</sub> + V/&phi;V<sub>n</sub> &le; 1.2. CY: (%.2f + %.2f)/1.2 = %.2f. Worst type: %s, (%.2f + %.2f)/1.2 = <b>%.2f</b>.</li>'], ...
   R.cone(j4).kTi, St.nT(j4), St.nT(j4), St.s(1,j4), St.int(1,j4), R.typ(jw).name, St.nT(jw), St.s(1,jw), St.int(1,jw));
w(['<li><b>Reading.</b> The top of the pedestal cuts the half cone (CY: %g mm above the anchors, &psi;<sub>ed,V</sub> = %.2f, A<sub>Vc</sub> cut), but H is small: the torsion couple has a %.0f mm lever arm down to the shear anchors. ' ...
   'Not counted: &psi;<sub>c,V</sub> = 1.2 for the &#216;16 column bars that run along the vertical edge between the anchors and the side face (Table 17.7.2.5.1), and the beams that frame into some side faces.</li>'], ...
   St.ctop(j4), St.pedV(2,j4), Y4.zT - S.zS);
w(['<li><b>If all four holes bear.</b> With V/4 on each top anchor the interaction reaches %.2f (E) and %.2f (CY): over 1 at E, so the concrete beside the top anchors could crack sideways. ' ...
   'Their share of V then moves to the shear anchors, which carry all of V on their own (section 8, worst %.2f). This is the same idea as case 2 of R17.7.2.1: a near anchor gives up its share and the others take it, because the holes are not welded. H stays on the top anchors, and that is the check above. ' ...
   'To make this certain rather than argued, the holes of the top anchors in the end plate can be slotted vertically, about 18 x 26 mm with a plate washer. The top anchors then never pick up V, but they still take H.</li>'], St.int(2,1), St.int(2,j4), max(sqrt(S.ell2)));
w('</ol></div></div>');
w('<div class="tw"><table><tr><th></th>');
for j = 1:4, w('<th>%s</th>', R.typ(j).name); end
w('</tr>');
lst = {'Top of the pedestal above the anchors, c<sub>a2</sub> (mm)', St.ctop, '%g'; 'H on the pair (kN)', [R.typ.Hc]*kN, '%.1f';
       'Shear, H only: largest ratio', St.s(1,:), '%.2f'; 'Tension, largest ratio', St.nT, '%.2f';
       'Tension + shear, H only (17.8.3, /1.2)', St.int(1,:), '%.2f';
       'If all 4 holes bear: tension + shear (information)', St.int(2,:), '%.2f'};
for k = 1:size(lst,1)
    w('<tr><td>%s</td>', lst{k,1});
    for j = 1:4, w(['<td>' lst{k,3} '</td>'], lst{k,2}(j)); end
    w('</tr>');
end
w('</table></div>');

% ---- 9. strut-and-tie models of the joint (ACI 318-19 chapter 23), written as small explicit steps
S6 = ca_stm(P, R, 0.6);  S8 = ca_stm(P, R, 0.8);  M = S6(1);  th = M.theta;  phi = 0.75;  q = M.p2;
Ase = an.Ase;  Ab12s = pi*P.cb.db^2/4;  Acol = pi*P.col.db^2/4;  rc = P.col.cover + P.col.dtie + P.col.db/2;
wV = bp.u - (P.col.b - rc - 8 - P.col.db/2);  An1 = 2*H.Abrg;  z1 = Y.zT;  z2 = M.z2;  Tk = M.T*kN;
xp = row('Pullout at the back plate');  xb = row('Side-face blowout');
ok_ = @(d) sprintf('<span class="%s">D/C = %.2f</span>', ifelse(d <= 1, 'ok', 'ng'), d);
w('<h2>9. Strut-and-tie models of the joint (ACI 318-19 chapter 23)</h2>');
w('<style>.st{border-collapse:collapse;margin:10px 0 14px 0;width:100%%;max-width:1000px}.st td{border:1px solid #ddd;padding:5px 9px;text-align:left;font-size:14.5px;line-height:1.5}.st td:first-child{width:95px;color:#555;background:#f6f6f6;font-size:13px}.st tr:first-child td{background:#eef3f8;font-weight:bold}.st tr:last-child td:last-child{font-weight:bold}</style>');
w(['<div class="calc" style="max-width:1000px"><p><b>In short.</b> A strut-and-tie model replaces the concrete of the joint by a truss: <b>struts</b> are concrete in compression, <b>ties</b> are steel in tension, ' ...
   '<b>nodes</b> are where they meet. If every part of one truss carries its force (23.3.1: &phi; &times; strength &ge; force, &phi; = 0.75, Table 21.2.1(g)), the joint is safe (a lower-bound result, R23.2.3). ' ...
   'R17.5.2.1 allows this method for the anchor reinforcement.</p>' ...
   '<p>Two trusses are checked, each carrying <b>all</b> of the pull on its own: <b>path 1</b> sends it into the beam top bars, <b>path 2</b> sends it diagonally down to the end plate''s push on the face. ' ...
   'If either one passes, the joint passes. Type E is worked out step by step; the other types are in the table of 9.4.</p></div>']);
w('<div class="row"><div><img src="figures/ta_stm.png" alt="STM"></div><div class="calc">');
w('<p><b>Starting numbers, type E</b></p><ul>');
w('<li>Pull on the two top anchors: <b>T = %.1f kN</b> (section 1)</li>', Tk);
w('<li>Anchors at z = %+g; back plate B1: %g high, %g wide, its bearing face at u = %g from the cantilever face</li>', z1, bp.h, bp.w, bp.u);
w('<li>Net bearing area of B1 (minus the 2 holes): %.0f mm&sup2;</li>', An1);
w('<li>Beam top bars (tie of path 1) at z = %g (the lower layer, conservative)</li>', z2);
w('<li>Concrete f''<sub>c</sub> = %.2f MPa; bars f<sub>y</sub> = %g MPa; anchors f<sub>ya</sub> = %g MPa</li>', fc, P.fy, an.fya);
w('</ul></div></div>');

% ---------------- path 1
w('<h3>9.1 Path 1: from the back plate into the beam top bars</h3><div class="calc" style="max-width:1000px">');
w(['<table class="st"><tr><td>Step 1</td><td>Choose the angle &theta; of the strut S1 (from B1 down to the beam bars)</td></tr>' ...
   '<tr><td>Rule</td><td>23.2.7: a strut must make at least 25&#176; with any tie at its node, so 25&#176; &le; &theta; &le; 65&#176; (the anchors and bars are horizontal, the column-bar tie is vertical). ' ...
   'Inside that range the designer may choose (R23.2.3, lower bound).</td></tr>' ...
   '<tr><td>How</td><td>Every angle from 25&#176; to 65&#176; was tried in 0.5&#176; steps. For each angle all the checks below were computed and the <b>worst</b> one noted. ' ...
   'The angle kept is the one whose worst check is <b>lowest</b> (that is what &ldquo;smallest largest D/C&rdquo; means). The checks at the anchor head (9.3) do not take part.</td></tr>' ...
   '<tr><td>Result</td><td>&theta; = %.1f&#176;</td></tr></table>'], th);
w(['<table class="st"><tr><td>Step 2</td><td>Forces in the truss</td></tr>' ...
   '<tr><td>Rule</td><td>Equilibrium at the back plate (23.2.4): the strut pushes back the pull T, so its horizontal part equals T: S1 cos&theta; = T. Its vertical part is held by the column bars: V = S1 sin&theta;.</td></tr>' ...
   '<tr><td>Numbers</td><td>S1 = T / cos&theta; = %.1f / cos %.1f&#176; = %.1f / %.3f = %.1f kN<br>V = T &times; tan&theta; = %.1f &times; tan %.1f&#176; = %.1f &times; %.3f = %.1f kN</td></tr>' ...
   '<tr><td>Result</td><td>strut S1 = %.1f kN; vertical tie V = %.1f kN; the beam bars carry T = %.1f kN</td></tr></table>'], ...
   Tk, th, Tk, cosd(th), M.Fs*kN, Tk, th, Tk, tand(th), M.V*kN, M.Fs*kN, M.V*kN, Tk);
w(['<table class="st"><tr><td>Step 3</td><td>Where the strut meets the beam bars (node N2)</td></tr>' ...
   '<tr><td>Rule</td><td>Geometry: the strut drops (z<sub>A1</sub> &minus; z<sub>bars</sub>) while it advances (z<sub>A1</sub> &minus; z<sub>bars</sub>)/tan&theta; towards the face.</td></tr>' ...
   '<tr><td>Numbers</td><td>drop = %g + %g = %g mm; advance = %g / %.3f = %.0f mm; u<sub>N2</sub> = %g &minus; %.0f = %.0f mm</td></tr>' ...
   '<tr><td>Result</td><td>N2 at u = %.0f mm from the cantilever face</td></tr></table>'], ...
   z1, -z2, z1 - z2, z1 - z2, tand(th), (z1 - z2)/tand(th), bp.u, (z1 - z2)/tand(th), M.u2, M.u2);
w(['<table class="st"><tr><td>Step 4</td><td>Tie A1: the two anchor rods</td></tr>' ...
   '<tr><td>Rule</td><td>23.7.2: F<sub>nt</sub> = A<sub>ts</sub> f<sub>y</sub>; check &phi;F<sub>nt</sub> &ge; T</td></tr>' ...
   '<tr><td>Numbers</td><td>&phi;F<sub>nt</sub> = 0.75 &times; 2 rods &times; %g mm&sup2; &times; %g MPa = %.1f kN; D/C = %.1f / %.1f</td></tr>' ...
   '<tr><td>Result</td><td>%s</td></tr></table>'], Ase, an.fya, phi*2*Ase*an.fya*kN, Tk, phi*2*Ase*an.fya*kN, ok_(M.dc(1)));
w(['<table class="st"><tr><td>Step 5</td><td>Tie of the beam top bars</td></tr>' ...
   '<tr><td>Rule</td><td>23.7.2: F<sub>nt</sub> = A<sub>ts</sub> f<sub>y</sub>, with the %d bars counted in section 5; check &phi;F<sub>nt</sub> &ge; T</td></tr>' ...
   '<tr><td>Numbers</td><td>&phi;F<sub>nt</sub> = 0.75 &times; %d bars &times; %.0f mm&sup2; &times; %g MPa = %.1f kN; D/C = %.1f / %.1f</td></tr>' ...
   '<tr><td>Result</td><td>%s</td></tr></table>'], M.n, M.n, Ab12s, P.fy, phi*M.n*Ab12s*P.fy*kN, Tk, phi*M.n*Ab12s*P.fy*kN, ok_(M.dc(2)));
w(['<table class="st"><tr><td>Step 6</td><td>Vertical tie V: the 2 far corner column bars &#216;%g (their hooks rest on the B1 nuts)</td></tr>' ...
   '<tr><td>Rule</td><td>23.7.2: &phi;F<sub>nt</sub> = 0.75 A<sub>ts</sub> f<sub>y</sub> &ge; V</td></tr>' ...
   '<tr><td>Numbers</td><td>&phi;F<sub>nt</sub> = 0.75 &times; 2 &times; %.0f mm&sup2; &times; %g MPa = %.1f kN; D/C = %.1f / %.1f</td></tr>' ...
   '<tr><td>Result</td><td>%s</td></tr></table>'], P.col.db, Acol, P.fy, phi*2*Acol*P.fy*kN, M.V*kN, phi*2*Acol*P.fy*kN, ok_(M.dc(3)));
w(['<table class="st"><tr><td>Step 7</td><td>Width of the strut S1 where it leaves B1</td></tr>' ...
   '<tr><td>Rule</td><td>Fig. R23.2.6b: w<sub>s</sub> = h<sub>B1</sub> cos&theta; + w<sub>V</sub> sin&theta;, with w<sub>V</sub> = %g mm, from the B1 face to the front of the column hooks that bring V in</td></tr>' ...
   '<tr><td>Numbers</td><td>w<sub>s</sub> = %g &times; %.3f + %g &times; %.3f = %.1f + %.1f = %.1f mm</td></tr>' ...
   '<tr><td>Result</td><td>w<sub>s</sub> = %.1f mm (it stays this wide in the plane down to N2)</td></tr></table>'], ...
   wV, bp.h, cosd(th), wV, sind(th), bp.h*cosd(th), wV*sind(th), M.ws, M.ws);
w(['<table class="st"><tr><td>Step 8</td><td>Node N2 on the beam bars: is the concrete there strong enough?</td></tr>' ...
   '<tr><td>Rule</td><td>23.9.1 and 23.9.2: allowed stress f<sub>ce</sub> = 0.85 &beta;<sub>c</sub> &beta;<sub>n</sub> f''<sub>c</sub>; &beta;<sub>n</sub> = 0.8 (one tie, Table 23.9.2(b)), &beta;<sub>c</sub> = 1 (no bearing plate, Table 23.4.3(b)(c)). ' ...
   'The strut arrives %.1f wide; across the joint it has widened from B1 (%g) to the group of bars, %.0f mm (R23.4.2).</td></tr>' ...
   '<tr><td>Numbers</td><td>allowed: &phi; f<sub>ce</sub> = 0.75 &times; 0.85 &times; 1 &times; 0.8 &times; %.2f = %.1f MPa<br>' ...
   'stress: S1 / (w<sub>s</sub> &times; width) = %.0f N / (%.1f mm &times; %.0f mm) = %.1f MPa; D/C = %.1f / %.1f</td></tr>' ...
   '<tr><td>Result</td><td>%s</td></tr></table>'], M.ws, bp.w, M.b2, fc, phi*M.fn2, M.Fs, M.ws, M.b2, M.Fs/(M.ws*M.b2), M.Fs/(M.ws*M.b2), phi*M.fn2, ok_(M.dc(6)));
zone = M.ws/sind(th);
w(['<table class="st"><tr><td>Step 9</td><td>Are the beam bars long enough beyond N2, towards their hooks?</td></tr>' ...
   '<tr><td>Rule</td><td>23.8.3: the tie must be developed from where it leaves the node zone. The zone is w<sub>s</sub>/sin&theta; long along the bars; the hook needs l<sub>dh</sub> = %.0f mm (25.4.3, section 5); ' ...
   'the outside of the hooks is taken %g mm further out than drawn (Table 26.6.2.1 tolerance).</td></tr>' ...
   '<tr><td>Numbers</td><td>zone length = %.1f / %.3f = %.0f mm, half = %.0f mm; zone ends at u = %.0f &minus; %.0f = %.0f<br>' ...
   'hooks end at u = %g + %g = %g; length available = %.0f &minus; %g = %.0f mm; D/C = %.0f / %.0f</td></tr>' ...
   '<tr><td>Result</td><td>%s</td></tr></table>'], H.ldh12, P.tol.ub, M.ws, sind(th), zone, zone/2, M.u2, zone/2, M.u2 - zone/2, ...
   P.cb.uh, P.tol.ub, P.cb.uh + P.tol.ub, M.u2 - zone/2, P.cb.uh + P.tol.ub, M.avail, H.ldh12, M.avail, ok_(M.dc(7)));
w('<p><b>Path 1 result, type E:</b> the worst check is %.2f (step %s). Every check passes.</p></div>', max(M.dc([1 2 3 6 7])), ifelse(M.dc(6) >= M.dc(7), '8', '9'));

% ---------------- path 2
w('<h3>9.2 Path 2: from the back plate diagonally down to the end plate''s push</h3><div class="calc" style="max-width:1000px">');
w(['<table class="st"><tr><td>Step 1</td><td>Where the end plate pushes on the face (node N3)</td></tr>' ...
   '<tr><td>Rule</td><td>The compression of the end plate is the bearing block of plate_check section 3 (AISC DG1): length Y from the bottom edge of the plate, width %g; its centre is the node.</td></tr>' ...
   '<tr><td>Numbers</td><td>bottom edge at z = %g; Y = %.0f mm; z<sub>N3</sub> = %g + %.0f / 2 = %.0f</td></tr>' ...
   '<tr><td>Result</td><td>N3 at u = 0, z = %.0f; it pushes with C = T = %.1f kN</td></tr></table>'], P.ep.w, Y.ep_bot, q.Y, Y.ep_bot, q.Y, q.z3, q.z3, Tk);
w(['<table class="st"><tr><td>Step 2</td><td>Angle of the strut from B1 to N3</td></tr>' ...
   '<tr><td>Rule</td><td>Fixed by the two nodes: tan&theta; = drop / distance; 23.2.7 asks 25&#176; to 65&#176;</td></tr>' ...
   '<tr><td>Numbers</td><td>drop = %g + %.0f = %.0f mm; distance = %g mm; &theta; = atan(%.0f / %g) = %.1f&#176;</td></tr>' ...
   '<tr><td>Result</td><td>&theta; = %.1f&#176; (within 25&#176; to 65&#176;)</td></tr></table>'], z1, -q.z3, z1 - q.z3, bp.u, z1 - q.z3, bp.u, q.theta, q.theta);
w(['<table class="st"><tr><td>Step 3</td><td>Forces</td></tr>' ...
   '<tr><td>Rule</td><td>As in path 1: S = T / cos&theta;, V = T tan&theta;</td></tr>' ...
   '<tr><td>Numbers</td><td>S = %.1f / %.3f = %.1f kN; V = %.1f &times; %.3f = %.1f kN</td></tr>' ...
   '<tr><td>Result</td><td>strut %.1f kN; column bars %.1f kN; the column below takes the moment</td></tr></table>'], Tk, cosd(q.theta), q.Fs*kN, Tk, tand(q.theta), q.V*kN, q.Fs*kN, q.V*kN);
w(['<table class="st"><tr><td>Step 4</td><td>Ties: anchors and column bars</td></tr>' ...
   '<tr><td>Rule</td><td>23.7.2, as steps 4 and 6 of path 1</td></tr>' ...
   '<tr><td>Numbers</td><td>anchors: %.1f / %.1f; column bars: %.1f / %.1f</td></tr>' ...
   '<tr><td>Result</td><td>anchors %s; column bars %s</td></tr></table>'], Tk, phi*2*Ase*an.fya*kN, q.V*kN, phi*2*Acol*P.fy*kN, ok_(q.dc(1)), ok_(q.dc(2)));
w(['<table class="st"><tr><td>Step 5</td><td>Node N3: bearing of the end plate on the face</td></tr>' ...
   '<tr><td>Rule</td><td>23.9.2: &beta;<sub>n</sub> = 1.0 (only compression meets here, Table 23.9.2(a)); &beta;<sub>c</sub> = %.2f (a bearing plate on a wide face, Table 23.4.3(b)(a))</td></tr>' ...
   '<tr><td>Numbers</td><td>allowed: 0.75 &times; 0.85 &times; %.2f &times; 1.0 &times; %.2f = %.1f MPa<br>stress: %.0f N / (%.0f mm &times; %g mm) = %.1f MPa; D/C = %.1f / %.1f</td></tr>' ...
   '<tr><td>Result</td><td>%s</td></tr></table>'], q.bc3, q.bc3, fc, phi*q.fn3, M.T, q.Y, P.ep.w, M.T/(q.Y*P.ep.w), M.T/(q.Y*P.ep.w), phi*q.fn3, ok_(q.dc(5)));
w(['<table class="st"><tr><td>Step 6</td><td>The strut where it arrives at N3</td></tr>' ...
   '<tr><td>Rule</td><td>23.4.1 and 23.4.3: allowed 0.85 &beta;<sub>c</sub> &beta;<sub>s</sub> f''<sub>c</sub>, &beta;<sub>s</sub> = 0.75 (strut in a beam-column joint, Table 23.4.3(a)(e)); width w = Y cos&theta; (conservative)</td></tr>' ...
   '<tr><td>Numbers</td><td>w = %.0f &times; %.3f = %.1f mm<br>allowed: 0.75 &times; 0.85 &times; %.2f &times; 0.75 &times; %.2f = %.1f MPa<br>stress: %.0f N / (%.1f mm &times; %g mm) = %.1f MPa; D/C = %.1f / %.1f</td></tr>' ...
   '<tr><td>Result</td><td>%s. This ratio is the same at any load: the bearing block grows with the load at a fixed stress.</td></tr></table>'], ...
   q.Y, cosd(q.theta), q.ws3, q.bc3, fc, phi*q.fs3, q.Fs, q.ws3, P.ep.w, q.Fs/(q.ws3*P.ep.w), q.Fs/(q.ws3*P.ep.w), phi*q.fs3, ok_(q.dc(6)));
As3c = 3*Acol;  dcol = P.col.b - rc;  a3c = As3c*P.fy/(0.85*fc*P.col.b);  phiMc = 0.9*As3c*P.fy*(dcol - a3c/2);
Mcol = hypot(Y.Mu, P.frame.Mcol*1e6);
w(['<table class="st"><tr><td>Step 7</td><td>The column below takes the moment</td></tr>' ...
   '<tr><td>Rule</td><td>22.4, no axial force; conservative: only the 3 bars on the tension face, no compression steel. Demand: all of the cantilever, plus the frame moment at right angles (as in revision 2).</td></tr>' ...
   '<tr><td>Numbers</td><td>a = %.0f &times; %g / (0.85 &times; %.2f &times; %g) = %.1f mm<br>&phi;M<sub>n</sub> = 0.9 &times; %.0f &times; %g &times; (%g &minus; %.1f/2) = %.1f kN m<br>' ...
   'demand = &radic;(%.1f&sup2; + %.1f&sup2;) = %.1f kN m; D/C = %.1f / %.1f</td></tr>' ...
   '<tr><td>Result</td><td>%s</td></tr></table>'], As3c, P.fy, fc, P.col.b, a3c, As3c, P.fy, dcol, a3c, phiMc*1e-6, Y.Mu*1e-6, P.frame.Mcol, Mcol*1e-6, Mcol*1e-6, phiMc*1e-6, ok_(Mcol/phiMc));
w('<p><b>Path 2 result, type E:</b> the worst check is %.2f. Every check passes.</p></div>', max(q.dc([1 2 4 5 6])));

% ---------------- N1: the anchor head
w('<h3>9.3 Node N1 at the back plate: the head of the anchors (information only)</h3><div class="calc" style="max-width:1000px">');
w(['<table class="st"><tr><td>What</td><td>The concrete just in front of B1, where both paths start</td></tr>' ...
   '<tr><td>Which rule</td><td>B1 is the head of the anchors. Chapter 17 checks a head with equations from tests on heads: pullout 17.6.3 <b>%s</b>, side blowout towards the pedestal top 17.6.4 <b>%s</b>. ' ...
   'Caveat: 17.1.5 leaves out one plate joining two anchors, so these are the closest checks, not a formal fit (decision of 2026-10-02: keep one B1).</td></tr>' ...
   '<tr><td>Chapter 23 (for comparison)</td><td>allowed: 0.75 &times; 0.85 &times; &beta;<sub>c</sub> %.2f &times; &beta;<sub>n</sub> 0.6 (two ties meet: anchors and column bars, Table 23.9.2(c)) &times; %.2f = %.1f MPa<br>' ...
   'stress on the B1 face: %.0f N / %.0f mm&sup2; = %.1f MPa; D/C = %.2f (with &beta;<sub>n</sub> = 0.8: %.2f)</td></tr>' ...
   '<tr><td>Why only information</td><td>The chapter 23 limit (about 1.0 f''<sub>c</sub>) is calibrated on nodes at bearing plates of deep beams; at an anchor head chapter 17 allows 8 f''<sub>c</sub> from tests. ' ...
   'The head has thin cover only towards the top, and the blowout check covers exactly that.</td></tr></table>'], ...
   ok_(xp{4}(1)/xp{5}(1)), ok_(xb{4}(1)/xb{5}(1)), M.bc, fc, phi*M.fn1, M.T, An1, M.T/An1, M.dc(4), S8(1).dc(4));
w('</div>');
w('<h3>9.4 All types</h3><div class="tw"><table><tr><th>Element</th><th>Clause</th><th class="n">E</th><th class="n">C1</th><th class="n">CX</th><th class="n">CY</th></tr>');
nm9 = {'Path 1: &theta; chosen (&#176;)', '23.2.7'; 'Tie A1', '23.7.2'; 'Tie, beam bars', '23.7.2'; 'Tie V, column bars', '23.7.2'; 'N1, B1 face (information, head: ch. 17)', '23.9.1'; ...
       'S1 at N1 (information, head: ch. 17)', '23.4.1'; 'N2 (S1 face)', '23.9.1'; 'Beam bars developed beyond N2', '23.8.3, 25.4.3'; '<b>Path 1, largest</b>', ''; 'Path 1, largest with N1 (information)', '';
       'Path 2: &theta; (&#176;)', '23.2.7'; 'Path 2: tie V', '23.7.2'; 'Path 2: strut at N1 (information, head: ch. 17)', '23.4.1'; 'Path 2: N3 face', '23.9.1'; 'Path 2: strut at N3', '23.4.1'; 'Path 2, largest with N1 (information)', ''; '<b>Path 2, largest</b>', ''};
info9 = [5 6 10 13 16];
for i = 1:numel(nm9)/2
    w('<tr><td>%s</td><td>%s</td>', nm9{i,1}, nm9{i,2});
    for j = 1:4
        if i == 1, v = S6(j).theta; w('<td class="n">%.1f</td>', v); continue; end
        if i == 11, v = S6(j).p2.theta; w('<td class="n">%.1f</td>', v); continue; end
        q2 = S6(j).p2.dc;
        if i <= 8, v = S6(j).dc(i - 1); elseif i == 9, v = max(S6(j).dc([1 2 3 6 7])); elseif i == 10, v = max(S6(j).dc);
        elseif i == 12, v = q2(2); elseif i == 13, v = q2(4); elseif i == 14, v = q2(5); elseif i == 15, v = q2(6);
        elseif i == 16, v = max(q2(1:6)); else, v = max(q2([1 2 4 5 6])); end
        if any(i == info9), w('<td class="n" style="color:#777">%.2f</td>', v); else, w('<td class="n %s">%.2f</td>', ifelse(v <= 1, 'ok', 'ng'), v); end
    end
    w('</tr>');
end
w('</table></div>');

% larger back plates
w('<h3>9.5 If the head were checked by chapter 23 too (information, type E, &beta;<sub>n</sub> = 0.6)</h3><div class="tw"><table><tr><th>B1</th><th class="n">N1 face</th><th class="n">S1 at N1</th><th class="n">N2</th><th class="n">bars beyond N2</th><th class="n">STM largest</th><th class="n">STM largest CY</th><th class="n">B1 itself: through the hole (section 3)</th></tr>');
for hw = [45 120; 60 120; 45 160; 60 160; 60 200]'
    P2 = P;  P2.bp.h = hw(1);  P2.bp.w = hw(2);  R2 = ca_calc(P2);  Sx = ca_stm(P2, R2, 0.6);  d1 = Sx(1).dc;   % theta still chosen without N1
    rh_ = R2.rows(find(strncmp(R2.rows(:,2), 'Back plate through the hole', 27), 1), :);  dh = rh_{4}(1)/rh_{5}(1);
    if all(hw' == [60 120]), big = [max(d1), max(arrayfun(@(q) max(q.dc), Sx))]; end
    w('<tr><td>PL %gx%gx%g</td><td class="n">%.2f</td><td class="n">%.2f</td><td class="n">%.2f</td><td class="n">%.2f</td><td class="n %s">%.2f</td><td class="n">%.2f</td><td class="n %s">%.2f</td></tr>', ...
      bp.t, hw(1), hw(2), d1(4), d1(5), d1(6), d1(7), ifelse(max(d1) <= 1, 'ok', 'ng'), max(d1), max(Sx(4).dc), ifelse(dh <= 1, 'ok', 'ng'), dh);
end
w('</table></div>');
w(['<div class="calc" style="max-width:1150px"><p><b>Reading.</b> Every tie is comfortable (0.3 to 0.65), so the steel of both load paths is complete and strong enough: that is what R17.5.2.1 asks a strut-and-tie model to prove. ' ...
   'The concrete away from the head also passes: path 1 at %.2f (E: the node on the beam bars and the bar length past it, which eases as soon as path 2 takes part of T), path 2 at %.2f. ' ...
   'At the head itself the chapter 23 node limit would give %.2f at E; a taller plate (PL 12x60x120) would bring it to %.2f, but the head is checked by chapter 17 (pullout %.2f, blowout %.2f), and the design keeps PL 12x45x120 (user, 2026-10-04).</p></div>'], ...
   max(S6(1).dc([1 2 3 6 7])), max(S6(1).p2.dc([1 2 4 5 6])), S6(1).dc(4), big(1), xp{4}(1)/xp{5}(1), xb{4}(1)/xb{5}(1));
w('<div class="calc" style="max-width:1150px"><h3>9.6 Review of the model (what was checked, what is assumed)</h3><ol>');
w('<li><b>Equilibrium</b> (23.2.4): path 1, the local couple T (z<sub>A1</sub> &minus; z<sub>bars</sub>) = %.2f kN m equals V (u<sub>N1</sub> &minus; u<sub>N2</sub>) = %.2f kN m, taken by the column; path 2, T (z<sub>A1</sub> &minus; z<sub>N3</sub>) = %.2f kN m equals V u<sub>N1</sub> = %.2f kN m and equals M<sub>u</sub> = %.2f kN m.</li>', ...
  M.T*(z1 - z2)*1e-6, M.V*(bp.u - M.u2)*1e-6, M.T*(z1 - M.p2.z3)*1e-6, M.p2.V*bp.u*1e-6, Y.Mu*1e-6);
w('<li><b>Angles</b> (23.2.7): every strut 25&#176; to 65&#176; from the horizontal ties and the vertical tie. <b>Factors</b>: &phi; 0.75 (Table 21.2.1(g)); &beta;<sub>s</sub> 0.75 for struts in a beam-column joint (Table 23.4.3(a)(e), no 23.5 reinforcement needed); &beta;<sub>n</sub> 1.0 / 0.8 / 0.6 by the number of ties (Table 23.9.2); &beta;<sub>c</sub> 2 only at bearing faces (B1, the end plate), 1 elsewhere (Table 23.4.3(b)).</li>');
w('<li><b>Assumed geometry</b>: N2 lies on the lower layer of beam bars (as in section 5); the strut reaching N2 widens out of the plane to the bar group (R23.4.2, tapered strut); at N3 the bearing block is the DG1 one; the vertical struts S2 and S3 into the column are wide and not checked; the width w<sub>V</sub> = %g at N1 (where the hooks bring V in) matters only for the information checks at the head.</li>', wV);
w('<li><b>23.11 not applied</b>: the strut-and-tie model carries the cantilever (gravity and E<sub>v</sub>), not the frame''s lateral force, as for the anchors in 17.10 (section 1 of the report: no E<sub>h</sub> on the cantilever); the frame is ordinary (user).</li>');
w('<li><b>What it does not replace</b>: chapter 17 for the anchors and their head, chapter 25 for the beam bars as anchor reinforcement (sections 2 to 6), and the beam and joint checks of the report.</li>');
w('</ol></div>');
w('</body></html>');
fclose(fid);
end

function r = ifelse(a, b, c)
if a, r = b; else, r = c; end
end

