function C = f_capacities(fname)
% F_CAPACITIES  Design strengths of the members around axis F (ACI 318-19, AISC 360-16 LRFD) and a
%   plain-text table for direct reference (axis_F/capacities.txt). Materials as in
%   cantilever_anchor_bolted_plate/ca_inputs.m: f'c 210 kg/cm2 (the calc stays at 210, user), fy 420,
%   steel sections A36 (Fy 248), IPAC 2023 IPE table.
if nargin < 1, fname = fullfile(fileparts(mfilename('fullpath')), 'capacities.txt'); end
fc = 210*0.0980665;  fy = 420;  fyt = 420;  Es = 200000;  Fy = 248;  lam = 1;
% ---- VCS 30x35, 3 Ø12 top + 3 Ø12 bottom, stirrups Ø10 (2 legs) @ 140 (as the VCM; to confirm) ------
V.b = 300;  V.h = 350;  V.cover = 40;  V.dst = 10;  V.db = 12;  V.n = 3;  V.s = 140;
V.d = V.h - V.cover - V.dst - V.db/2;                         % 294
V.As = V.n*pi*V.db^2/4;
a = V.As*fy/(0.85*fc*V.b);
V.phiMn = 0.9*V.As*fy*(V.d - a/2);                            % same both signs (3 + 3)
V.Asmin = max(0.25*sqrt(fc)/fy, 1.4/fy)*V.b*V.d;              % 9.6.1.2
V.Vc = 0.17*lam*sqrt(fc)*V.b*V.d;                             % 22.5.5.1 (Av >= Av,min)
Av = 2*pi*V.dst^2/4;  V.Vs = Av*fyt*V.d/V.s;
V.phiVc = 0.75*V.Vc;  V.phiVn = 0.75*(V.Vc + V.Vs);
Acp = V.b*V.h;  pcp = 2*(V.b + V.h);
V.phiTth = 0.75*0.083*lam*sqrt(fc)*Acp^2/pcp;                 % 22.7.4.1(a): below it, torsion may be neglected
V.phiTcr = 4*V.phiTth;                                        % 22.7.5.1: cracking torsion (compatibility limit)
x1 = V.b - 2*(V.cover + V.dst/2);  y1 = V.h - 2*(V.cover + V.dst/2);
V.Aoh = x1*y1;  V.ph = 2*(x1 + y1);  V.Ao = 0.85*V.Aoh;
At = pi*V.dst^2/4;
V.phiTn = 0.75*2*V.Ao*At*fyt/V.s;                             % 22.7.6.1, theta 45, closed stirrups with 135 deg hooks
V.Almin = min(0.42*sqrt(fc)*Acp/fy - (At/V.s)*V.ph*fyt/fy, 0.42*sqrt(fc)*Acp/fy - (0.175*V.b/fyt)*V.ph*fyt/fy);   % 9.6.4.3
C.VCS = V;
% ---- steel sections (IPAC 2023, A36) ------------------------------------------------------------
cat = fullfile(fileparts(mfilename('fullpath')), '..', '..', '..', 'digitalized_catalog_profiles', 'ipac2023', 'ipac_ipe.csv');
T = csv_rows(cat);
for nm = {'IPE 140', 'IPE 160', 'IPE 180', 'IPE 200', 'IPE 240'}
    r = T(strcmp(T(:,1), nm{1}), :);  g = str2double(r(2:end));
    S.name = nm{1};  S.h = g(1);  S.tw = g(2);  S.b = g(3);  S.tf = g(4);  S.r = g(5);
    S.A = g(8)*1e2;  S.Ix = g(10)*1e4;  S.Sx = g(11)*1e3;  S.Iy = g(13)*1e4;  S.ry = g(15)*10;  S.Zx = g(16)*1e3;  S.J = g(18)*1e4;
    S.ho = S.h - S.tf;  S.Cw = S.Iy*S.ho^2/4;  S.rts = sqrt(sqrt(S.Iy*S.Cw)/S.Sx);
    S.Mp = Fy*S.Zx;  S.phiMp = 0.9*S.Mp;
    S.Lp = 1.76*S.ry*sqrt(Es/Fy);
    jc = S.J/(S.Sx*S.ho);
    S.Lr = 1.95*S.rts*Es/(0.7*Fy)*sqrt(jc + sqrt(jc^2 + 6.76*(0.7*Fy/Es)^2));
    S.phiVn = 1.0*0.6*Fy*S.h*S.tw;                            % G2.1(a): h/tw small, phi = 1, Cv1 = 1
    S.phiMn = @(Lb, Cb) 0.9*mn_ltb(S, Fy, Es, Lb, Cb);
    C.(strrep(nm{1}, ' ', '')) = S;
end
% ---- text table ----------------------------------------------------------------------------------
f = fopen(fname, 'w');
fprintf(f, 'DESIGN STRENGTHS, members around axis F (generated by f_capacities.m; do not edit by hand)\n');
fprintf(f, 'ACI 318-19 / AISC 360-16 LRFD. f''c = %.1f MPa (210 kg/cm2), fy = %g, steel A36 Fy = %g. kN, kN m.\n\n', fc, fy, Fy);
fprintf(f, 'VCS 30x35, 3 Ø12 top + 3 Ø12 bottom, stirrups Ø10 2 legs @ %g (ASSUMED as the VCM: confirm), d = %g\n', V.s, V.d);
fprintf(f, '  phi Mn (+ and -)                 %7.1f   (As = %.0f mm2, As,min = %.0f)\n', V.phiMn/1e6, V.As, V.Asmin);
fprintf(f, '  phi Vc / phi Vn                  %7.1f / %.1f\n', V.phiVc/1e3, V.phiVn/1e3);
As4 = 4*pi*V.db^2/4;  a4 = As4*fy/(0.85*fc*V.b);
fprintf(f, '  phi Mn + with 4 Ø12 bottom       %7.1f   (user 2026-10-05: one more bottom bar between B-C and C-D)\n', 0.9*As4*fy*(V.d - a4/2)/1e6);
fprintf(f, '  phi T threshold (22.7.4.1a)      %7.2f   below it torsion may be neglected\n', V.phiTth/1e6);
fprintf(f, '  phi T cracking (compatibility)   %7.2f   22.7.3.2 cap for compatibility torsion\n', V.phiTcr/1e6);
fprintf(f, '  phi Tn, closed stirrups 135 deg  %7.1f   with Al = (At/s) ph = %.0f mm2 extra longitudinal at phi Tn (in proportion to Tu); Al,min 9.6.4.3\n', V.phiTn/1e6, At/V.s*V.ph);
for nm = {'IPE140', 'IPE160', 'IPE180', 'IPE200', 'IPE240'}
    S = C.(nm{1});
    fprintf(f, '\n%s (A36): A %.0f mm2, Ix %.0f cm4, Zx %.0f cm3, ry %.1f mm, J %.1f cm4\n', S.name, S.A, S.Ix/1e4, S.Zx/1e3, S.ry, S.J/1e4);
    fprintf(f, '  phi Mp                           %7.1f   (Lb <= Lp = %.0f mm)\n', S.phiMp/1e6, S.Lp);
    fprintf(f, '  phi Mn, Cb = 1: Lb = 1.0 / 1.27 / 1.45 / 2.4 / 4.78 m:  %.1f / %.1f / %.1f / %.1f / %.1f   (Lr = %.0f mm)\n', ...
        S.phiMn(1000, 1)/1e6, S.phiMn(1270, 1)/1e6, S.phiMn(1450, 1)/1e6, S.phiMn(2400, 1)/1e6, S.phiMn(4780, 1)/1e6, S.Lr);
    fprintf(f, '  phi Vn                           %7.1f\n', S.phiVn/1e3);
end
fclose(f);
fprintf('%s\n', fname);
end

function Mn = mn_ltb(S, Fy, Es, Lb, Cb)
% AISC 360-16 F2.2
if Lb <= S.Lp
    Mn = S.Mp;
elseif Lb <= S.Lr
    Mn = min(S.Mp, Cb*(S.Mp - (S.Mp - 0.7*Fy*S.Sx)*(Lb - S.Lp)/(S.Lr - S.Lp)));
else
    x = Lb/S.rts;
    Fcr = Cb*pi^2*Es/x^2*sqrt(1 + 0.078*S.J/(S.Sx*S.ho)*x^2);
    Mn = min(S.Mp, Fcr*S.Sx);
end
end

function T = csv_rows(fn)
% rows of a simple csv as a cell array of strings (header dropped)
L = strsplit(strtrim(fileread(fn)), char(10));
T = cellfun(@(s) strsplit(strtrim(s), ','), L(2:end), 'UniformOutput', false);
T = vertcat(T{:});
end
