"""Write lib/sheets/STYLES.md from the printers (run after adding a style):
    python3 lib/printing/styles_md.py"""
import importlib.util
import os

here = os.path.dirname(os.path.abspath(__file__))
spec = importlib.util.spec_from_file_location("pour_pdf", os.path.join(here, "pour_pdf.py"))
m = importlib.util.module_from_spec(spec)
spec.loader.exec_module(m)
J = m.J
S = J.Style(1.0)
GUIDE = """## Which style for what (the usual choices)
| piece | style |
|---|---|
| plans: concrete beams / concrete columns | m_conc / m_col (c_member, c_column_mark) |
| plans: steel members, one colour per section | m1 ... m8 (and c_legend) |
| concrete cut / seen; cast before (faint) | r_conc / r_old |
| column bars: solid / faint | r_colS / r_col |
| beam bars (in line, second pair, crossing, bottom) | r_bm1, r_bm2, r_bm3, r_bm4 |
| extra bars (bastones, added bars) | r_bas (or r_new) |
| ties: solid / faint | r_tieS / r_tie |
| anchor rods: cast in / after the pour (dashed) | r_anc / r_ancg |
| nuts and washers | r_nut (or r_ancg) |
| head plates / end plates / grout | r_bp / r_eplate / r_grout |
| steel profile: body / flanges | r_ipe / r_ipef (or plate, column, beam) |
| grid line, bubble | axis, bubble |
| leaders, cut lines, hidden | lead, cut, hidden |
| joint marker (c_node) | r_oval_l |
| texts: normal, small, bold, red | label, small, code, red |
| texts by colour family: anchors, hooks/bastones, new bars, ties, beam bars | anc, hk, new, tie, bsm |
"""
out = ["# Styles (the `s` argument of d_* and c_*)", "",
       "Every style below exists when the sheet is printed with `lib/printing/pour_pdf.py`",
       "(sheet_pdf uses it). An unknown shape style falls back silently, so check the name",
       "here. Generated by lib/printing/styles_md.py.", "", GUIDE,
       "## Shapes (stroke, width pt, fill, dash)", "",
       "| style | stroke | width | fill | dash |", "|---|---|---|---|---|"]
for k, (st, w, f, op, dash) in J.SHAPE.items():
    out.append(f"| {k} | {st or '-'} | {w} | {f or '-'} | {'yes' if dash else '-'} |")
out += ["", "## Texts (font, size pt at fs = 1, colour)", "", "| style | font | size | colour |", "|---|---|---|---|"]
for k, (font, size, col) in S.text.items():
    out.append(f"| {k} | {'bold' if 'Bold' in font else 'regular'} | {size:.1f} | {col} |")
with open(os.path.join(here, "..", "sheets", "STYLES.md"), "w") as f:
    f.write("\n".join(out) + "\n")
